export default [
  {
    taxonName: 'Dasysyrphus',
    author: 'Enderlein, 1938',
    url: '/otus/950163/overview',
    keyUrl: '',
    introduction: `Enderlein (1938) introduced <i>Dasysyrphus</i> as a subgenus of <i>Syrphus</i>. It was not recognized as a valid genus until the revisions by Hippa (1968) and Vockeroth (1969). The latter author proposed a close relationship between <i>Dasysyrphus</i> and <i>Notosyrphus</i>, despite differences in the structure of the male genitalia. However, this relationship has not been supported by recent molecular data (e.g., Mengual et al., 2015, 2018). Based on molecular evidence, Mengual et al. (2018) suggested a close relationship between <i>Dasysyrphus</i> and <i>Melangyna</i>.`,
    diagnosis: `Within Syrphinae, <i>Dasysyrphus</i> species can be readily separated from all other genera by the following combination of characters: yellow face and scutellum; hairy eyes; absence of yellow bands on scutum; anterior part of the anepisternum without long hairs; marginated abdomen; metasternum bare; black abdomen with yellow markings; abdominal markings usually separated and constricted medially; R4+5 without loop. `,
    description: `
      <p>The face is yellow with a central black stripe extending from the base of the antennae to the oral margin (absent in <i>D. hilaris</i>). The oral margin is usually black, though it may be entirely yellow in rare cases (e.g., <i>D. albostriatus</i>). The eyes are densely pilose. Males are holoptic, females dichoptic. The frons is black, though it may be yellow around the antennae in some species (e.g., <i>D. albostriatus</i>). Antennae are simple and black. The frons is shiny, with variable tomentose markings.</p>
      
      <p>The scutum is black and glossy, bearing two tomentose vittae on its anterior half (four vittae occur only in <i>D. eggeri</i>), although these are distinctly visible only in <i>D. albostriatus</i> and <i>D. eggeri</i>. The scutal hairs are long and range from entirely yellow to a mix of black and yellow. The scutellum is yellow and bears long hairs, ranging from completely black to predominantly yellow with some interspersed black hairs. The pleura are entirely black and shiny, with well-developed tomentose areas on the posterior part of the anepisternum and the dorsal side of the katepisternum in some species. The pleural hairs are long and yellow. The metasternum is bare.</p>
        
      <p>Legs are simple and predominantly yellow, with black areas variably present on the femora and hind tibiae depending on the species. The leg hairs are long, either yellow or mixed black and yellow. Wings are hyaline with a distinct black pterostigma and are almost entirely covered with microtrichia. The abdomen is oval and marginated, with yellow markings present on tergites 2–5. The markings are usually separated but may be medially confluent in <i>D. trincinctus</i> and occasionally in <i>D. albostriatus</i>. The yellow markings may or may not connect to the lateral margins of the abdomen. Sternites are yellow with a centrally developed black area of varying extent.</p>
        
      <p>In males, the epandrium is trapezoidal, with the hypandrium rounded ventrally. Surstyli are triangular and apically narrowed. Cerci are oval and bear long hairs. The postgonite exhibits variable morphology. The distiphallus is elongate and distally enlarged, except in <i>D. albostriatus</i> and <i>D. eggeri</i>.</p>    
    `,
    biology: `The larvae of the genus are zoophagous. Based on the limited available data, they feed on aphids, as well as a wide variety of other insect larvae (e.g., sawflies, flies, lepidopterans). Larvae have predominantly been found in association with trees, and more rarely on shrubs and herbaceous plants. Adults are typically found in woodland habitats, including both coniferous and deciduous forests. Most species are univoltine, with the exception of <i>D. albostriatus</i> and <i>D. tricinctus</i>, which are bivoltine. Only <i>D. albostriatus</i> and <i>D. friulensis</i> have been recorded as migratory species.`,
    biodiversity: `Fifty species have been described (Evenhuis and Pape, 2025), most of which originate from the Holarctic region. Only a few species (less than ten) are known from the Oriental region. The genus is absent from Australia and likely from South America as well. Thirty-one species are known from the Palaearctic region, thirteen of which have been reported from Europe (Reverté et al., 2023). Vockeroth (1969) divided the genus into four species groups. Locke & Skevington (2013) revised the Nearctic fauna and, based on morphological and molecular analyses, proposed four species groups: the <i>D. albostriatus</i>, <i>D. pinastri</i>, <i>D. tricinctus</i>, and <i>D. venustus`,
    italianBiodiversity: `
      <p>In Italy eleven species of <i>Daysyrphus</i> have been recorded, most of which occur in mountainous regions. Only <I>D</I>. <i>albostriatus</i>, <I>D</I>. <i>pinastri</i>, <I>D</I>. <i>tricinctus</i> and <I>D</I>. <i>venustus</i> have been reported from Central and Southern Italy. <I>D</I>. <i>albostriatus</i> and <I>D</I>. <i>tricinctus</i> are the only species known to occur in Sicily, while no records exist for Sardinia. In Northern Italy, all species are known to occur, although only <i>D. albostriatus</i> has been documented from the Padania Plain.</p>
        
      <p>For species-level identification, European keys may be used, although they remain incomplete. For instance, van Veen (2004) does not include <i>D. postclaviger</i> and <i>D. neovenustus</i>; Bartsch (2009) omits <i>D. lenensis</i> and <i>D. neovenustus</i>; and Bot & De Meutter (2023) exclude <i>D. eggeri</i> and <i>D. postclaviger</i></p>
    `
  },
  {
    taxonName: 'Didea',
    author: 'Macquart, 1834',
    url: '/otus/950498/overview',
    keyUrl: '',
    introduction: `Macquart (1834) introduced the genus <i>Didea</i> for the new species <i>Didea fasciata</i> Macquart 1834. Few years later Meigen (1838) described the genus <i>Enica</i> for the new species <i>Enica foesteri</i> Meigen, 1838 now considered as synonym of <i>Didea</i>. The genus <i>Didea</i> is well characterized, and it has been accepted by following authors (e.g. Rondani, 1857; Verrall, 1901; Bezzi and Stein, 1907). Recent phylogenetic studies based on molecular data confirmed the validity of the genus <i>Didea</i>, with a well-supported clade between: <i>Eriozona</i> Schiner, 1860 + (<i>Didea</i> Macquart, 1838 + <i>Megasyrphus</i> Dušsek & Laska, 1967) (Mengual et al., 2015, 2023). `,
    diagnosis: `Within Syrphinae, <i>Didea</i> species can be readily separated from all other genera by the loop in vein R4+5; in addition the abdomen is large and flattened with yellow or white spots and evident lateral margin.`,
    description: `
      <p>The face is completely yellow in <I>D</I>. <i>fasciata</i>, or yellow with a central black stripe extending from the base of the antennae to the oral margin. The oral margin is completely yellow in <I>D</I>. <i>fasciata</i>, or yellow with a black anterior part. The eyes are bare. Males are holoptic, females dichoptic. In males the frons is yellow in males, sometimes with black spots around the base of the antennae. In females the frons is black, with the anterior third yellow; two distinct tomentose markings are present adjacent to the eyes, giving the black area the shape of an inverted Y. The antennae are black or black with reddish ventro-basal area. The basoflagellomere is elongated (twice as long as it is wide) and pointed apically.</p>
      
      <p>The scutum is black and shiny, with long yellow hairs. The scutellum is yellow, bearing black spots only on the anterolateral angles, in <I>D</I>. <i>alneti</i> the entire apical portion of the scutellum is black. The scutellar hairs are yellow, with black hairs present on the posterior part.  The pleura are black and covered by tomentosity, which is especially evident on the katepisternum and the posterior part of the anepisternum. The pleural hairs are long and yellow or white. The metasternum is hairy.</p>
        
      <p>Legs are simple and black, except for the front and middle femora (black only at base), front and middle tibiae (completely yellow) and the knees of posterior legs. The leg hairs are black, long only on the posterior half of the femora. The wings are hyaline with a distinct black pterostigma. They are almost entirely covered with microtrichia, with bare areas possibly present only on cells bm and br. An evident loop is present on vein R4+5. The halteres may be yellow or black at the apex.</p>
        
      <p>The abdomen is oval, flat and marginated, with yellow or white markings (white in <I>D</I>. <i>alneti</i>) present on tergites 2–4, and in some species also on tergite 5. The markings on tergites 2 are medially separated, while those on tergites 3 and 4 are usually connected. The markings of tergite 2 are confluent with the lateral margin, whereas those of tergites 3 and 4 vary depending on the species. The sternites are yellow, with a centrally developed black area on the posterior margin, with variable extent.</p>

      <p>In males, the epandrium is trapezoidal, with the hypandrium ventrally convex. The surstyli are broad and apically truncated in <I>D</I>. <i>fasciata</i>; whereas in the other species the sustylus have a distinct dorsal  notch. The cerci are oval and bear long hairs. The postgonite is very large in <I>D</I>. <i>fasciata</i>, small in the other species. The distiphallus is very large and sclerotized in <I>D</I>. <i>fasciata</i>; in the other species, it is short, thick and heavily sclerotized.</p>    
    `,
    biology: `The larvae of the genus are zoophagous. They have been recorded only feeding on aphids associated with trees, both conifers (e.g. <i>Larix</i>, <i>Pinus</i>) and deciduous species (<i>Salix</i>, <i>Prunus</i>, <i>Quercus</i>). All species overwinter in the larval stage. Adults are typically found in woodland habitats. The species are univoltine or bivoltine and are non-migratory or weakly migratory.`,
    biodiversity: `<i>Didea</i> is a small genus including only eight species currently considered valid (Evenhuis and Pape, 2025). Five species are known from Holoarctic region, three from India. The genus is absent from the Oriental, Neotropical and Afrotropical regions. Three species are known Europe (Reverté et al., 2023).`,
    italianBiodiversity: `All European species have been recorded in Italy. <i>Didea fasciata</i> is the only species recorded throughout the country, including Sardinia and Sicily. The other two species are restricted to mountainous areas in Northern and Central Italy. For species-level identification, European keys can be used.`,
    references: [
  "Bezzi, M., Stein P. (1907). Cyclorrapha Aschiza. Cyclorrapha Schizophora: Schizometopa. In: Becker, T., Bezzi, M., Kertész, K., Stein, P. (eds.): Katalog der palaarktischen Dipteren, Vol. 3. Budapest. Pp. 1-188.",
  "Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. http://diptera.org/ [accessed on 25.08.2025]",
  "Macquart, P.J.M. (1834). Histoire naturelle des insectes. Diptères. Tome premiere. Roret, Paris. 578 pp.",
  "Meigen, J.W. (1838). Systematische Beschreibung der bekannten europäischen zweiflügeligen Insekten. Siebenter Theil oder Supplementband. Schultz, Hamm. 434 pp.",
  "Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 48: 250-277.",
  "Mengual, X.; Ståhls, G.; Rojo, S. (2015). Phylogenetic relationships and taxonomic ranking of pipizine flower flies (Diptera: Syrphidae) with implications for the evolution of aphidophagy. Cladistics, 31: 491-508.",
  "Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.",
  "Rondani, C. (1857). Dipterologiae italicae prodromus. Vol: II. Species italicae ordinis dipterorum in genera characteribus definita, ordinatim collectae, methodo analitica distinctae, et novis vel minus cognitis descriptis. Pars prima. Oestridae: Syrphidae: Conopidae. A. Stocchi, Parmae, 264 pp.",
  "Verrall, G.H. (1901). British flies. Vol. VIII, Platypezidae, Pipunculidae and Syrphidae of Great Britain. Gurney & Jackson, London, 691 pp."
]
}


]
