export default [
  {
    taxonName: 'Dasysyrphus',
    author: 'Enderlein, 1938',
    url: '/otus/950163/overview',
    keyUrl: '/keys/2694',
    keyUrlEN: '',
    introduction: `Enderlein (1938) introduced <i>Dasysyrphus</i> as a subgenus of <i>Syrphus</i>. It was not recognized as a valid genus until the revisions by Hippa (1968) and Vockeroth (1969). The latter author proposed a close relationship between <i>Dasysyrphus</i> and <i>Notosyrphus</i>, despite differences in the structure of the male genitalia. However, this relationship has not been supported by recent molecular data (e.g., Mengual et al., 2015, 2023). Based on molecular evidence, Mengual et al. (2018) suggested a close relationship between <i>Dasysyrphus</i> and <i>Melangyna</i>.`,
    diagnosis: `Within Syrphinae, <i>Dasysyrphus</i> species can be readily separated from all other genera by the following combination of characters: yellow face and scutellum; hairy eyes; absence of yellow bands on scutum; anterior part of the anepisternum without long hairs; marginated abdomen; metasternum bare; black abdomen with yellow markings; abdominal markings usually separated and constricted medially; R4+5 without loop.  `,
    description: `
      <p>The face is yellow with a central black stripe extending from the base of the antennae to the oral margin (absent in <i>D. hilaris</i>). The oral margin is usually black, though it may be entirely yellow in rare cases (e.g., <i>D. albostriatus</i>). The eyes are densely pilose. Males are holoptic, females dichoptic. The frons is black, though it may be yellow around the antennae in some species (e.g., <i>D. albostriatus</i>). Antennae are simple and black. The frons is shiny, with variable tomentose markings.</p>
      
      <p>The scutum is black and glossy, bearing two tomentose vittae on its anterior half (four vittae occur only in <i>D. eggeri</i>), although these are distinctly visible only in <i>D. albostriatus</i> and <i>D. eggeri</i>. The scutal hairs are long and range from entirely yellow to a mix of black and yellow. The scutellum is yellow and bears long hairs, ranging from completely black to predominantly yellow with some interspersed black hairs. The pleura are entirely black and shiny, with well-developed tomentose areas on the posterior part of the anepisternum and the dorsal side of the katepisternum in some species. The pleural hairs are long and yellow. The metasternum is bare.</p>
        
      <p>Legs are simple and predominantly yellow, with black areas variably present on the femora and hind tibiae depending on the species. The leg hairs are long, either yellow or mixed black and yellow. Wings are hyaline with a distinct black pterostigma and are almost entirely covered with microtrichia. The abdomen is oval and marginated, with yellow markings present on tergites 2–5. The markings are usually separated but may be medially confluent in <i>D. trincinctus</i> and occasionally in <i>D. albostriatus</i>. The yellow markings may or may not connect to the lateral margins of the abdomen. Sternites are yellow with a centrally developed black area of varying extent.</p>
        
      <p>In males, the epandrium is trapezoidal, with the hypandrium rounded ventrally. Surstyli are triangular and apically narrowed. Cerci are oval and bear long hairs. The postgonite exhibits variable morphology. The distiphallus is elongate and distally enlarged, except in <i>D. albostriatus</i> and <i>D. eggeri</i>.</p>    
    `,
    biology: `The larvae of the genus are zoophagous. Based on the limited available data, they feed on aphids, as well as a wide variety of other insect larvae (e.g., sawflies, flies, lepidopterans). Larvae have predominantly been found in association with trees, and more rarely on shrubs and herbaceous plants. Adults are typically found in woodland habitats, including both coniferous and deciduous forests. Most species are univoltine, with the exception of <i>D. albostriatus</i> and <i>D. tricinctus</i>, which are bivoltine. Only <i>D. albostriatus</i> and <i>D. friulensis</i> have been recorded as migratory species.`,
    biodiversity: `Fifty species have been described (Evenhuis and Pape, 2025), most of which originate from the Holarctic region. Only a few species (less than ten) are known from the Oriental region. The genus is absent from Australia and likely from South America as well. Thirty-one species are known from the Palaearctic region, thirteen of which have been reported from Europe (Reverté et al., 2023). Vockeroth (1969) divided the genus into four species groups. Locke & Skevington (2013) revised the Nearctic fauna and, based on morphological and molecular analyses, proposed four species groups: the <i>D. albostriatus</i>, <i>D. pinastri</i>, <i>D. tricinctus</i>, and <i>D. venustus.`,
    italianBiodiversity: `
      <p>In Italy eleven species of <i>Daysyrphus</i> have been recorded, most of which occur in mountainous regions. Only <I>D</I>. <i>albostriatus</i>, <I>D</I>. <i>pinastri</i>, <I>D</I>. <i>tricinctus</i> and <I>D</I>. <i>venustus</i> have been reported from Central and Southern Italy. <I>D</I>. <i>albostriatus</i> and <I>D</I>. <i>tricinctus</i> are the only species known to occur in Sicily, while no records exist for Sardinia. In Northern Italy, all species are known to occur, although only <i>D. albostriatus</i> has been documented from the Padania Plain.</p>
        
      <p>For species-level identification, European keys may be used, although they remain incomplete. For instance, van Veen (2004) does not include <i>D. postclaviger</i> and <i>D. neovenustus</i>; Bartsch et al. (2009) omits <i>D. lenensis</i> and <i>D. neovenustus</i>; and Bot & De Meutter (2023) exclude <i>D. eggeri</i> and <i>D. postclaviger</i>.</p>
    `,
    references: [
  "Bartsch, H., Binkiewicz, E., Rådén, A., Nasibov, E. (2009) Blomflugor: Syrphinae. Nationalnyckeln till Sveriges flora och flora, DH53a. Artdatabanken, SLU, Uppsala. 406 pp.",
  "Bot, S., van de Meutter, F. (2023). Hoverflies of Britain and North-west Europe. A photographic guide. Bloomsbury Wildlife, London, 400 pp.",
  "Enderlein, G., (1938). Beitrag zur Kenntnis der Syrphiden. Sitzungsberichte der Gesellschaft Naturforschender Freunde Berl. 1937: 192-237.",
  "Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href=\"http://diptera.org/\" target=\"_blank\">http://diptera.org/</a> [accessed on 25.08.2025].",
  "Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.",
  "Locke, M.M., Skevington, J.H. (2013) Revision of Nearctic <i>Dasysyrphus</i> Enderlein (Diptera: Syrphidae). Zootaxa, 3660 (1), 1–80. <a href=\"https://doi.org/10.11646/zootaxa.3660.1.1\" target=\"_blank\">https://doi.org/10.11646/zootaxa.3660.1.1</a>",
  "Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 2023, 48: 250-277.",
  "Mengual, X.; Ståhls, G.; Rojo, S. (2015). Phylogenetic relationships and taxonomic ranking of pipizine flower flies (Diptera: Syrphidae) with implications for the evolution of aphidophagy. Cladistic, 2015: 491-508.",
  "Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.",
  "Vockeroth, J.R., (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176."
]
  },
  {
    taxonName: 'Didea',
    author: 'Macquart, 1834',
    url: '/otus/950498/overview',
    keyUrl: '',
    keyUrlEN: '',
    introduction: `Macquart (1834) introduced the genus <i>Didea</i> for the new species <i>Didea fasciata</i> Macquart 1834. Few years later Meigen (1838) described the genus <i>Enica</i> for the new species <i>Enica foesteri</i> Meigen, 1838 now considered as synonym of <i>Didea</i>. The genus <i>Didea</i> is well characterized, and it has been accepted by following authors (e.g. Rondani, 1857; Verrall, 1901; Bezzi and Stein, 1907). Recent phylogenetic studies based on molecular data confirmed the validity of the genus <i>Didea</i>, with a well-supported clade between: <i>Eriozona</i> Schiner, 1860 + (<i>Didea</i> Macquart, 1838 + <i>Megasyrphus</i> Dušsek & Laska, 1967) (Mengual et al., 2015, 2023). `,
    diagnosis: `Within Syrphinae, <i>Didea</i> species can be readily separated from all other genera by the loop in vein R4+5; in addition the abdomen is large and flattened with yellow or white spots and evident lateral margin.`,
    description: `
      <p>The face is completely yellow in <I>D</I>. <i>fasciata</i>, or yellow with a central black stripe extending from the base of the antennae to the oral margin. The oral margin is completely yellow in <I>D</I>. <i>fasciata</i>, or yellow with a black anterior part. The eyes are bare. Males are holoptic, females dichoptic. In males the frons is yellow in males, sometimes with black spots around the base of the antennae. In females the frons is black, with the anterior third yellow; two distinct tomentose markings are present adjacent to the eyes, giving the black area the shape of an inverted Y. The antennae are black or black with reddish ventro-basal area. The basoflagellomere is elongated (twice as long as it is wide) and pointed apically.</p>
      
      <p>The scutum is black and shiny, with long yellow hairs. The scutellum is yellow, bearing black spots only on the anterolateral angles, in <I>D</I>. <i>alneti</i> the entire apical portion of the scutellum is black. The scutellar hairs are yellow, with black hairs present on the posterior part.  The pleura are black and covered by tomentosity, which is especially evident on the katepisternum and the posterior part of the anepisternum. The pleural hairs are long and yellow or white. The metasternum is hairy.</p>
        
      <p>Legs are simple and black, except for the front and middle femora (black only at base), front and middle tibiae (completely yellow) and the knees of posterior legs. The leg hairs are black, long only on the posterior half of the femora. The wings are hyaline with a distinct black pterostigma. They are almost entirely covered with microtrichia, with bare areas possibly present only on cells bm and br. An evident loop is present on vein R4+5. The halteres may be yellow or black at the apex.</p>
        
      <p>The abdomen is oval, flat and marginated, with yellow or white markings (white in <I>D</I>. <i>alneti</i>) present on tergites 2–4, and in some species also on tergite 5. The markings on tergites 2 are medially separated, while those on tergites 3 and 4 are usually connected. The markings of tergite 2 are confluent with the lateral margin, whereas those of tergites 3 and 4 vary depending on the species. The sternites are yellow, with a centrally developed black area on the posterior margin, with variable extent.</p>

      <p>In males, the epandrium is trapezoidal, with the hypandrium ventrally convex. The surstyli are broad and apically truncated in <I>D</I>. <i>fasciata</i>; whereas in the other species the sustylus have a distinct dorsal  notch. The cerci are oval and bear long hairs. The postgonite is very large in <I>D</I>. <i>fasciata</i>, small in the other species. The distiphallus is very large and sclerotized in <I>D</I>. <i>fasciata</i>; in the other species, it is short, thick and heavily sclerotized.</p>    
    `,
    biology: `The larvae of the genus are zoophagous. They have been recorded only feeding on aphids associated with trees, both conifers (e.g. <i>Larix</i>, <i>Pinus</i>) and deciduous species (<i>Salix</i>, <i>Prunus</i>, <i>Quercus</i>). All species overwinter in the larval stage. Adults are typically found in woodland habitats. The species are univoltine or bivoltine and are non-migratory or weakly migratory.`,
    biodiversity: `<i>Didea</i> is a small genus including only eight species currently considered valid (Evenhuis and Pape, 2025). Five species are known from Holoarctic region, three from India. The genus is absent from the Oriental, Neotropical and Afrotropical regions. Three species are known Europe (Reverté et al., 2023).`,
    italianBiodiversity: `All European species have been recorded in Italy. <i>Didea fasciata</i> is the only species recorded throughout the country, including Sardinia and Sicily. The other two species are restricted to mountainous areas in Northern and Central Italy. For species-level identification, European keys can be used.`,
    references: [
  "Bezzi, M., Stein P. (1907). Cyclorrapha Aschiza. Cyclorrapha Schizophora: Schizometopa. In: Becker, T., Bezzi, M., Kertész, K., Stein, P. (eds.): Katalog der palaarktischen Dipteren, Vol. 3. Budapest. Pp. 1-188.",
  "Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href=\"http://diptera.org/\" target=\"_blank\">http://diptera.org/</a> [accessed on 25.08.2025].",
  "Macquart, P.J.M. (1834). Histoire naturelle des insectes. Diptères. Tome premiere. Roret, Paris. 578 pp.",
  "Meigen, J.W. (1838). Systematische Beschreibung der bekannten europäischen zweiflügeligen Insekten. Siebenter Theil oder Supplementband. Schultz, Hamm. 434 pp.",
  "Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 48: 250-277.",
  "Mengual, X.; Ståhls, G.; Rojo, S. (2015). Phylogenetic relationships and taxonomic ranking of pipizine flower flies (Diptera: Syrphidae) with implications for the evolution of aphidophagy. Cladistics, 31: 491-508.",
  "Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.",
  "Rondani, C. (1857). Dipterologiae italicae prodromus. Vol: II. Species italicae ordinis dipterorum in genera characteribus definita, ordinatim collectae, methodo analitica distinctae, et novis vel minus cognitis descriptis. Pars prima. Oestridae: Syrphidae: Conopidae. A. Stocchi, Parmae, 264 pp.",
  "Verrall, G.H. (1901). British flies. Vol. VIII, Platypezidae, Pipunculidae and Syrphidae of Great Britain. Gurney & Jackson, London, 691 pp."
]
},
{
    taxonName: 'Doros',
    author: 'Meigen, 1803',
    url: '/otus/950502/overview',
    keyUrl: '',
    keyUrlEN: '',
    introduction: `The genus Doros was established by Meigen (1803) including two species: <i>Syrphus conopseus</i> Linnaeus, 1758 sensu Fabricius, 1775 and <i>Syrphus coarctatus</i> Panzer, 1797, both currently considered synonyms of <i>Musca profuges</i> Harris, 1776. The genus <i>Doros</i> is well-defined, and has been accepted by subsequent authors (e.g. Rondani, 1857; Schiner, 1857; Verrall, 1901; Bezzi and Stein, 1907). With the exception of Sack (1930) which placed <i>Doros</i> in the Bacchinae due to its petiolate abdomen, the genus has consistently been associated with the tribe Syrphini (e.g. Vockeroth, 1969; Peck, 1988). Morphology of adults and larvae suggested a similarity between <i>Doros</i> and <i>Xanthogramma</i> (Duśek & Láska, 1967; Rotheray & Gilbert, 1999). Recent phylogenetic studies based on molecular data have confirmed a sister-group relationship between <i>Doros</i> and <i>Xanthogramma</i> (Mengual et al., 2018).`,
    diagnosis: `Within Syrphinae, <i>Doros</i> species can be readily separated from all other genera by the petiolate abdomen and the brown markings on the anterior part of the wing.`,
    description: `
<p>The face is completely yellow in <I>D</I>. <i>destillatorius</i>, or yellow with a central black stripe extending from the base of the antennae to the oral margin in <I>D</I>. <i>profuges</i>. The oral margin is black. The eyes are bare. Males are holoptic, females dichoptic. The frons is yellow, with a black central stripe, enlarging towards the antennae. The vertex is black. No tomentose markings is present on frons. The antennae are black or brown. The basoflagellomere is circular or little longer than larger.</p> 
<p>The scutum is black and shiny, with lateral yellow vittae along the entire scutum; two yellow or reddish spots may be present on the posterior margin of the scutum. The hairs on the scutum are short, adpressed, and either yellow or a mix of yellow and black. The scutellum is yellow, bearing black spots only on the anterolateral angles. Its hairs are short and yellow; few longer yellow hairs are present on the posterior half in males. The pleura are black, with a yellow spot on the dorsal part of the katepisternum. Pleural hairs are yellow - short in females and long in males. The hairs on the katepisternum are widely separated in the central part. The metasternum is bare.</p>
<p>The legs are simple and predominantly yellow. The front and middle femora are black at the base, with the dark coloration more extended on the posterior half. The hind femora are mostly black, with the base and knees yellow. The last tarsomeres of the front and middle legs, as well as all tarsomeres of the hind legs are, dorsally black. Leg hairs are short and yellow, long only on the posterior half of the front and middle femora. The wings are dark brown in the anterior half and hyaline in posterior portion. They are almost entirely covered with microtrichia, except for bare areas present on cells bm and br. The halteres are black with the yellow apices.</p>
<p>The abdomen is petiolate, with the second tergite approximately three times longer than wide and lacking a defined margin. The abdomen is black with yellow markings on tergites 2–5. These markings are most prominent on the second tergite, where the yellow spots extend from the anterior margin almost to the posterior edge. On the remaining tergites, the yellow spots are restricted to the anterior margin, except on the fourth tergite, which also bears a triangular yellow spot on the posterior margin. The sternites are black, except the second one which is yellow with the posterior margin of the first sternite and the anterior margins of the third and fourth sternites are yellow. Abdominal hairs are short and mostly black.</p> 
<p>In males, the epandrium is trapezoidal, with the hypandrium rounded ventrally. The surstyli are short and  broad. The cerci are oval and bear long hairs. The postgonite is short, semicircular with a posterodorsal hook. The distiphallus is slender, slightly swollen ventrally.</p> 
`,
    biology: `The larvae are zoophagous, probably associated with aphids tended by ants of the genus <i>Lasius</i>. Adults are typically found in deciduous woods (<i>Fagus</i>, <i>Quercus</i>, <i>Fraxinus</i>), usually with overmature trees. All species overwinter in the larval stage. They are univoltine and non-migratory.`,
    biodiversity: `<i>Didea</i> is a small genus comprising only four valid species (Evenhuis and Pape, 2025). The genus has a Holoarctic distribution, with three species occurring in the Palaearctic region and one in the Nearctic. Two species are known to be present in Europe (Reverté et al., 2023). There has been considerable nomenclatural confusion regarding the European species of <i>Doros</i>. Several authors have treated <i>D. destillatorius</i> as a synonym of <i>D. conopseus sensu </i>Fabricius, effectively reducing the genus to a single species in Europe (e.g. Peck, 1988). Thompson et al. (1982) reinstated <i>D. profuges</i> as a valid species in place of <i>D. conopseus</i> sensu Fabricius, while Speight (1988) clarified the distinctions between <i>D. profuges</i> and <i>D. destillatorius</i>.`,
    italianBiodiversity: `All European species have been recorded in Italy. This is an uncommon species, and only a few records are available for the country; these are scattered across the Italian mainland. <i>Doros destillatorius</i> has also been recorded from Sardinia.`,
    references: [
"Bezzi, M., Stein P. (1907). Cyclorrapha Aschiza. Cyclorrapha Schizophora: Schizometopa. In: Becker, T., Bezzi, M., Kertész, K., Stein, P. (eds.): Katalog der palaarktischen Dipteren, Vol. 3. Budapest. Pp. 1-188.",
"Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.",
"Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href=\"http://diptera.org/\" target=\"_blank\">http://diptera.org/</a> [accessed on 25.08.2025]",
"Meigen, J.W. (1803): Versuch einer neuen Gattungs-Eintheilung der europäischen zweiflügligen Insekten. Magazin für Insektenkunde 2: 259-281.",
"Mengual, X., Ståhls, G., Láska, P., Mazánek, L., Rojo, S. (2018). Molecular phylogenetics of the predatory lineage of flower flies Eupeodes–Scaeva (Diptera: Syrphidae), with the description of the Neotropical genus Austroscaeva gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56(2), 148–169. <a href=\"https://doi.org/10.1111/jzs.12212\" target=\"_blank\">https://doi.org/10.1111/jzs.12212</a>",
"Peck, L.V. (1988) Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.",
"Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.",
"Rondani, C. (1857). Dipterologiae italicae prodromus. Vol: II. Species italicae ordinis dipterorum in genera characteribus definita, ordinatim collectae, methodo analitica distinctae, et novis vel minus cognitis descriptis. Pars prima. Oestridae: Syrpfhidae: Conopidae. A. Stocchi, Parmae, 264 pp.",
"Rotheray, G.E., Gilbert, F. (1999). Phylogeny of Palaearctic Syrphidae (Diptera): evidence from larval stages. Zoological Journal of the Linnean Society, 127(1), 1–112. <a href=\"https://doi.org/10.1111/j.1096-3642.1999.tb01305.x\" target=\"_blank\">https://doi.org/10.1111/j.1096-3642.1999.tb01305.x</a>",
"Sack, P. (1930). 31. Syrphidae [part]. In: Lindner, E. (ed.): Die Fliegen der Palaearktischen Region 4(6): 177-240",
"Schiner, I.R. (1863). Fauna Austriaca. \"1864\" Theil II. Heft 11/12: 289-480.",
"Speight, M.C.D. (1988). <i>Doros destillatorius</i>, espèece nouvelle pour la France, avec désignation des types des deux espèces européennes du genre <i>Doros</i>, description de leurs pupes et clès de détermination des adultes et des pupes. Bulletin de la Société entomologique de France,<i> </i>92(5-6): 193- 200.",
"Thompson, F.C., Vockeroth, J.R., Speight, M.C.D., 1982. The Linnaean species of flower flies (Diptera: Syrphidae). Memoirs of the Entomological Society of Washington 10: 150-165",
"Verrall, G.H. (1901). British flies. Vol. VIII, Platypezidae, Pipunculidae and Syrphidae of Great Britain. Gurney & Jackson, London, 691 pp.",
"Vockeroth, J.R., (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176."
]
},
{
    taxonName: 'Epistrophe',
    author: 'Walker, 1852',
    url: '/otus/950604/overview',
    keyUrl: '',
    keyUrlEN: '',
    introduction: `<p>Although the genus <i>Epistrophe</i> was introduced by Walker (1852), it has traditionally been regarded as a junior synonym of <i>Syrphus</i> Fabriucius, 1775 (e.g. Verrall, 1901; Bezzi & Stein, 1907). Later authors recognized <i>Epistrophe</i> as a valid genus, albeit in a broader sense than it is understood today. For example, Sack (1930) included within <i>Epistrophe</i> several species that are now classified under <i>Parasyrphus</i>, <i>Episyrphus</i>, <i>Meligramma</i> and <i>Melangyna</i>.</p>
<p>It was only through the revision of <i>Syrphus</i> and allied genera—primarily based on male genitalia—that the boundaries of <i>Epistrophe</i> became more clearly defined (Duśek & Láska, 1967; Hippa, 1968; Vockeroth, 1969). The genus is often divided into two subgenera: <i>Epistrophe</i> and <i>Epistrophella</i> (Peck, 1988; van Veen, 2004; Bertollo & Sommaggio, 2012). Recent molecular studies have not only confirmed the validity of <i>Epistrophe</i> as a monophyletic group but have also highlighted that <i>Epistrophella</i> should be considered a distinct genus (Mengual et al., 2008; 2023). <i>Epistrophe</i> undoubtedly belongs to the tribe Syrphini, but its phylogenetic position remains unresolved. Mengual et al. (2008) proposed a clade consisting of (<i>Epistrophe</i> + <i>Chrysotoxum</i>) + (<i>Xanthogramma</i> + <i>Epistrophella</i>). More recently, Mengual et al. (2023) suggested a different arrangement: (<i>Epistrophe</i> + <i>Afrosyrphus</i>) + <i>Epistrophella</i>) + <i>Leucozona</i>.</p>
`,
    diagnosis: `The genus <i>Epistrophe</i> includes morphologically diverse species, characterized by the consistency of male terminalia, particularly in the shape of the surstyli, development of the lingula, and form of the aedeago. The species of this genus are medium to large-sized, generally with broad yellow bands on tergites 3–5. The thorax lacks distinct longitudinal yellow vittae (although some species may show faint vittae); the calypters are hairless on the upper part, the metasternum is bare, the face is entirely yellow, the eyes are bare, the wings have no spots, and vein R4+5 is straight. The abdomen is marginated, at least tergites 4 and 5.`,
    description: `
<p>The face is yellow and covered with yellow hairs. The oral margin may be either yellow or black. The eyes are bare. Males are holoptic, females dichoptic. The frons varies in coloration, ranging from entirely black to entirely yellow, and features extended tomentose areas. The hairs on the frons are also variable, from completely black to completely yellow. The antennae are simple and may be entirely black (e.g., <i>E. glossulariae</i>, <i>E. leiophthalma</i>) or show varying degrees of yellowish coloration on the ventral side (e.g., <i>E. diaphana</i>, <i>E. nitidicollis</i>).</p>
<p>The scutum is black and tomentose, even if in a few species (e.g. <I>E</I>. <i>eligans</i>, <I>E</I>. <i>nitidicollis</i>) it may be shiny. Scutal hairs are long and yellow. The scutellum is yellow and bears long yellow hairs; in few species ((e.g. <I>E</I>. <i>glossulariae</i>) some black hairs may be present along its posterior margin. The pleura are entirely black and largely covered with tomentosity; in <I>E</I>. <i>glossulariae,</i> the dorsal part of keterpisternum and and katepimeron may be yellow. Pleural hairs are long and yellow. The metasternum is bare.</p>
<p>The legs are simple and predominantly yellow, with the tarsomeres of the hind legs being black. In a few species (e.g., <i>E. glossulariae</i>, <i>E. leiophthalma</i>), the bases of the front and middle femora may be black. Leg hairs are long on the femora and shorter on tibiae and taromeres. The hairs are generally yellow, with, on the hind leg, black hairs on the distal portion of the femora and on the tibiae of hind legs; however this varies among species (e.g. entirely yellow in <I>E</I>. <i>leiophthalma</i>).  The wings are hyaline and completely covered with microtrichia, except in some species where cells bm and br may have bare areas. The halteres are yellow. No long hairs are present on the dorsal surface of the calyptres.</p>
<p>Abdominal markings are highly variable among <i>Epistrophe</i> species. The most common pattern consists of two large yellow spots on the second tergite and a yellow band on tergites 3–5. In <i>E. leiophthalma</i>, the abdomen is black with distinct tomentose spots on tergites 2–5. In <i>E. eligans</i>, the yellow bands vary in size, with the band on tergite 3 being larger than those on tergites 4 and 5; in darker specimens, the latter bands may be absent. Tergite hairs are generally yellow, with black hairs present along the posterior margins. The tergites are slightly marginated only on segments 4 and 5. Sternites are usually entirely yellow and bear long yellow hairs; however, this pattern may vary among species, with the posterior sternites being partially or entirely black to varying degrees.</p>
<p>In males, the epandrium is trapezoidal, and the hypandrium is ventrally rounded. The surstyli are short, nearly square, apically truncated. The hypandrium bears a consistently present lingula, which is broad and well-developed, though shorter than the postgonites. The postgonites are long and narrow. The cerci are oval and bear long hairs. The basiphallus is strongly laterally compressed, being much higher than long, and bears two prominent teeth at its base. The distiphallus is slightly longer than the basiphallus.</p>
`,
    biology: `The larvae of the genus are zoophagous. They exhibit pronounced dorsal flattening, resulting in a distinctly flattened body shape. Typically green in color, they are well adapted to preying on aphids found on deciduous trees (reported, for example, on <i>Acer</i>, <i>Prunus</i>, <i>Malus</i>, <i>Sambucus</i>) as well as on tall broad-leaved herbs such as <i>Cichorium</i>. Adults are typically found in deciduous woodland habitats; a few northern European species have also been recorded in coniferous forests. <i>Epistrophe eligans</i> and <I>E</I>. <i>nitidicollis</i> can also be found in anthropized habitat such as hedgerow and urban garden. Most species overwinter in the soil, typically beneath trees. All species are univoltine, with adults emerging early in spring. No species within the genus is migratory.`,
    biodiversity: `Fifty-three species have been described to date (Evenhuis & Pape, 2025). The genus is particularly species-rich in the Eastern Palaearctic region, with more than 20 species described from China in recent publications (Huo et al., 2007; Hao et al., 2012). Only a few species are present in the Nearctic and Oriental regions, while the genus is absent from the Afrotropical and Australian regions. Twelve species have been recorded in Europe (Reverté et al., 2023). Doczkal & Schmid (1994) revised the German fauna of the genus, describing three new species.`,
    italianBiodiversity: `<p>Only 7 of the 12 European species are present in Italy. Among these, <i>E. eligans</i> is the most common, occurring throughout the country, including the major islands. Another widespread species is <i>E. nitidicollis</i>, although no records currently exist for the major islands. The remaining five species are less frequent and are found primarily in northern and central Italy. <i>Epistrophe leiophthalma</i>, <i>E. diaphana</i>, and <i>E. glossulariae</i> are predominantly montane, while the other species are associated with lowland woodlands.</p>
<p>For species identification, the available European keys (e.g., van Veen, 2004; Bot & van de Meutter, 2023) include all Italian species. Particular caution should be exercised when interpreting records predating the work of Doczkal & Schmid (1994), as considerable confusion previously existed within the genus. For example, Italian records of <i>E. ochrostoma</i> are likely erroneous, as this species is native to central and northern Europe.</p>
`,
    references: [
"Bertollo, S., Sommaggio, D. (2012). Riconoscere i Sirfidi: la chiave dicotomica ai generi italiani. Quaderni Stazione di Ecologia Museo civico di Storia Naturale di Ferrara, 20: 101-145.",  
"Bezzi, M., Stein P. (1907). Cyclorrapha Aschiza. Cyclorrapha Schizophora: Schizometopa. In: Becker, T., Bezzi, M., Kertész, K., Stein, P. (eds.): Katalog der palaarktischen Dipteren, Vol. 3. Budapest. Pp. 1-188.",  
"Bot, S., van de Meutter, F. (2023). Hoverflies of Britain and North-west Europe. A photographic guide. Bloomsbury Wildlife, London, 400 pp.",  
"Doczkal, D., Schimd, U. (1994). Drei neue Arten der Gattung <i>Epistrophe</i> (Diptera: Syrphidae), mit einem Bestimmungsschlussel fur der deutschen Arten. Stuttgarter Beiträge zur Naturkunde (A) 507: 1-32.",  
"Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.",  
"Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href=\"http://diptera.org/\" target=\"_blank\">http://diptera.org/</a> [accessed on 25.08.2025].",  
"Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.",  
"Hao, X.L., Huo, K.K., Ren, B.Z. (2012). Two new species of the genus <i>Epistrophe</i> from Jilin Province (Diptera, Syrphidae). Acta Zootaxonomica Sinica 37: 199-202.",  
"Huo, K.K., Ren, G.D., Zheng, Z.M. (2007). Fauna of Syrphidae from Mt. Qinling-Bashan in China (Insecta: Diptera). Beijing Huonzheng., Beijing. 512 pp.",  
"Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 48: 250-277. <a href=\"https://doi.org/10.1111/syen.12573\" target=\"_blank\">https://doi.org/10.1111/syen.12573</a>.",  
"Mengual, X., Ståhls, G. & Rojo, S. (2008). First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href=\"https://doi.org/10.1111/j.1096-0031.2008.00200.x\" target=\"_blank\">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>.",  
"Peck, L.V. (1988). Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.",  
"Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.",  
"Sack, P. (1930). 31. Syrphidae [part]. In: Lindner, E. (ed.): Die Fliegen der Palaearktischen Region 4(6): 177-240.",  
"Veen, van M.P. (2004). Hoverflies of Northwest Europe. Identification keys to the Syrphidae. KNNV Publishing, 254 pp.",  
"Verrall, G.H. (1901). British flies. Vol. VIII, Platypezidae, Pipunculidae and Syrphidae of Great Britain. Gurney & Jackson, London, 691 pp.",  
"Vockeroth, J.R. (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176."
]
},
{
    taxonName: 'Epistrophella',
    author: 'Dušek & Láska, 1967',
    url: '/otus/985203/overview',
    keyUrl: '',
    keyUrlEN: '',
    introduction: `<p>The genus <i>Epistrophella</i> was introduced by Duśek & Láska (1967) to include the single species <i>Syrphus</i> <i>euchroma</i> Kowarz, 1885 and was considered the genus closely related to <i>Epistrophe</i> Walker, 1852. Most authors (e.g. Vockeroth, 1969; Peck, 1988; van Veen, 2004; Bertollo and Sommaggio, 2012) treated <i>Epistrophella</i> as a subgenus of <i>Epistrophe</i>. Based on larval characteristics, Rotheray and Gilbert (1989) confirmed Hippa's (1968) position, which included <i>E. euchroma</i> in the genus <i>Meligramma</i>. This classification was later followed by Speight (2020). Subsequent authors added species to the genus <i>Epistrophella</i>, notably <i>E. emarginata</i> (Say, 1823) and <i>E. horishama</i> (Matsumura, 1917) by Vockeroth (1969), and <i>E. coronata</i> (Rondani, 1957) by Doczkal and Vujić (1998). However, these species exhibit significant differences compared to <i>E. euchroma</i>, and therefore their actual assignment to the genus <i>Epistrophella</i> remains doubtful (Doczkal and Vujić, 1998; Speight, 2020). Recent molecular studies, based on the type species <I>E</I>. <i>euchroma</i>, have confirmed the validity of <i>Epistrophella </i>as a distinct genus (Mengual et al., 2008, 2018, 2023), regarded as the outgroup to the <i>Epistrophe</i> + <i>Afrosyrphus</i> clade (Mengual et al., 2023) and phylogenetically separated from <i>Meligramma</i>.</p>`,
    diagnosis: `The few species of the genus <i>Epistrophella</i> closely resemble those of <i>Epistrophe</i>, with which they share the following characteristics: the calypters are hairless on the upper part, the metasternum is bare, the face is yellow with black oral margin, the eyes are bare, the wings have no spots, and vein R4+5 is straight. However, they can be distinguished from <i>Epistrophe</i> by their abdomen with parallel margins (oval in <i>Epistrophe</i> and in <i>Epistrophella coronata</i>) and unmarginated sides (whereas <i>Epistrophe</i> typically shows marginal lines at least on tergites 3 and 4). Additionally, the abdomen displays separate yellow spots (generally fused in <i>Epistrophe</i>) and more prominent yellow vittae on the mesonotum (absent or barely visible in <i>Epistrophe</i>). <i>Epistrophella euchroma</i> may be confused with the genus <i>Meligramma</i>, but it differs by having abdominal spots separated from the lateral margin and a black oral margin, whereas in <i>Meligramma</i> the abdominal spots merge with the oral margin and/or the face is entirely yellow.`,
    description: `
<p>The face is yellow with a black oral margin; facial hairs are yellow. The eyes are bare. Males are holoptic, females dichoptic. The frons is black - entirely tomentose in males, with central tomentose spots in females. Frontal hairs are black or a mix of yellow and black. The antennae are simple and may be entirely black (<i>E. coronata</i>) or yellowish (<i>E. euchroma</i>).</p>
<p>The scutum is black and shiny, with yellow along the lateral margins. Scutal hairs are long and yellow. The scutellum is yellow, with black restricted to the anterior lateral angles, and bears long yellow hairs. The pleura are black and largely covered with tomentum; yellow spots may be present on the proepimeron, posterior anepisternum, dorsally on the katepisternum, katepimeron and katatergum. Pleural hairs are long, apically wavy and yellow. The metasternum is bare.</p>
<p>The legs are simple and yellow, with black spots on the femora, usually more developed on the hind femora. Leg hairs are long on the femora and shorter on tibiae and tarsomeres. Hairs are yellow on the front and middle legs (with a few black hairs possibly present on the tibiae); hairs on the hind legs are yellow on the coxae, trochanters and basal half of femora, and black on the remaining portions. The wings are hyaline and completely covered with microtrichia, except for small bare areas on cells bm and br. The halteres are yellow. No long hairs are present on the dorsal surface of the calyptres.</p>
<p>The abdomen has parallel margins on <I>E</I>. <i>euchroma</i>, and is more oval in <I>E</I>. <i>coronata</i>. It is black with yellow sport, which are separated from the lateral margins. In <I>E.</I> <i>coronata,</i> the spots are present only on tergites 2 and 3. Tergite hairs are yellow, with black hairs along the posterior margins. The tergites are unmarginated. Sternites are yellow with black lateral margins. Sternite hairs are yellow, with black hairs present on the terminal sternites.</p> 
<p>In males, the epandrium is trapezoidal, and the hypandrium is ventrally rounded. The surstyli are short, apically tapered. The hypandrium bears a consistently present lingula, which is broad and well-developed, though shorter than the postgonites. The postgonites are small and nearly square. The cerci are oval and bear long hairs. The basiphallus is strongly laterally compressed, being much higher than long, and bears small teeth at its base. The distiphallus is long, angular and bears numerous setae on its ventral-apical portion.</p>
`,
    biology: `The larvae of the genus are zoophagous. They exhibit pronounced dorsal flattening, resulting in a distinctly flattened body shape. The larvae feed on aphids on trees and shrubs (<i>Euonymus, Prunus)</i>, including trees in orchard. Adults are typically found in deciduous woodland habitats; <i>E. euchroma</i> can also be found in orchards. Epistrophella species overwinter in the soil, as larvae. All species are univoltine, with adults emerging early in spring. No species within the genus is migratory.`,
    biodiversity: `Evenhuis & Pape, 2025 recorded only four species in the genus Epistrophella. All species are Holoarctic, with three species in the Palaearctic region and only one in the Nearctic regione. Two species have been recorded in Europe (Reverté et al., 2023). `,
    italianBiodiversity: `Both European species are present in Italy. <i>Epistrophella euchroma</i> is the most common, occurring only on mailand; some records of this species are from the Alps while only two records from Central and Southern Italy are available. <i>Epistrophella coronata</i> is very rare; this species has been described by Rondani (1857) and this is the only record for Italy. Doczkal and Vujić (1998) provide a useful comparison between the two species.`,
    references: [
"Bertollo, S., Sommaggio, D. (2012). Riconoscere i Sirfidi: la chiave dicotomica ai generi italiani. Quaderni Stazione di Ecologia Museo civico di Storia Naturale di Ferrara, 20: 101-145.",  
"Doczkal, D., Vujic, A. (1998) Redescription of <i>Epistrophella coronata</i> (Rondani, 1857), stat.rest., comb.nov., with first description of the male and notes on the generic assignment. Volucella, 3: 51-62.",  
"Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.",  
"Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href=\"http://diptera.org/\" target=\"_blank\">http://diptera.org/</a> [accessed on 25.08.2025].",  
"Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.",  
"Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 48: 250-277. <a href=\"https://doi.org/10.1111/syen.12573\" target=\"_blank\">https://doi.org/10.1111/syen.12573</a>.",  
"Mengual, X., Ståhls, G., Láska, P., Mazánek, L., & Rojo, S. (2018). Molecular phylogenetics of the predatory lineage of flower flies <i>Eupeodes</i>–<i>Scaeva</i> (Diptera: Syrphidae), with the description of the Neotropical genus <i>Austroscaeva</i> gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56(2), 148–169. <a href=\"https://doi.org/10.1111/jzs.12212\" target=\"_blank\">https://doi.org/10.1111/jzs.12212</a>.",  
"Mengual, X., Ståhls, G. & Rojo, S. (2008) First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href=\"https://doi.org/10.1111/j.1096-0031.2008.00200.x\" target=\"_blank\">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>.",  
"Peck, L.V. (1988) Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.",  
"Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.",  
"Rotheray, G.E., Gilbert, F.S. (1989). The phylogeny and systematics of European predaceous Syrphidae (Diptera) based on larval and puparial stages. Zoological Journal of the Linnean Society, 95: 29-70.",  
"Speight, M.C.D. (2020). Species accounts of European Syrphidae, 2020. Syrph the Net, the database of European Syrphidae (Diptera), vol. 104, 314 pp., Syrph the Net publications, Dublin.",  
"Veen, van M.P. (2004). Hoverflies of Northwest Europe. Identification keys to the Syrphidae. KNNV Publishing, 254 pp.",  
"Vockeroth, J.R. (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176."
]
},
{
    taxonName: 'Episyrphus',
    author: 'Matsumura, 1917',
    url: '/otus/985428/overview',
    keyUrl: '',
    keyUrlEN: '',
    introduction: `<p>Matsumura and Adachi (1917) introduced the genus <i>Episyrphus</i>, designating the newly described species <i>Episyrphus fallaciosus</i> Matsumura, 1917 (a junior synonym of <i>Episyrphus balteatus</i> (De Geer, 1776)), as the type species. The genus was subsequently regarded as a junior synonym of <i>Syrphus</i> (e.g. Coe, 1953). Seguy (1961) treated <i>Episyrphus</i> as a valid genus, although he included species that are now considered to belong to <i>Melangyna</i> Verrall, 1901, <i>Meliscaeva</i> Frey, 1946 and <i>Epistrophella</i> Duśek & Láska, 1967. It was only in the late 1960 that the genus was properly defined (Duśek & Láska, 1967; Hippa. 1968; Vockeroth, 1969). Currently, the genus is divided into two subgenera: <i>Asiobaccha</i> Violovitsh, 1976 and <i>Episyrphus</i> s.s. (Thompson and Vockeroth 1989). Species within <i>Episyrphus</i> are morphologically similar to those of <i>Meliscaeva</i>, and some authors (e.g. van Veen, 2004) have included both under <i>Episyrphus</i>. Recent molecular studies have confirmed the strong phylogenetic relationship among <i>Episyrphus</i> (<i>Episyrphus</i>), <i>Episyrphus</i> (<i>Asiobaccha</i>) and <i>Meliscaeva</i>, with <i>Meliscaeva</i> as the outgroup of the other two taxa (Mengual et al., 2008, 2018, 2023).</p>`,
    diagnosis: `The species of the genera <i>Episyrphus</i> and <i>Meliscaeva</i> can be readily distinguished from all other Syrphinae by the combination of two morphological characters: the presence of hairs on the anterior part of the anepisternum and the sclerotized setal bases along the wing margin, which give the margin  the appearance of a series of black spots. <i>Episyrphus</i> can be separated from <i>Meliscaeva</i> by the presence of a tuft of pile beneath the spiracle of the metepimeron. However, in the Western Palaearctic region, the only species of <i>Episyrphus</i> present (<I>E</I>. <i>balteatus</i>) is easily recognized by its distinctive abdominal pattern, featuring a double yellow band on each tergites 3 and 4.`,
    description: `
<p>The face is enterely yellow, including the oral margin; facial hairs are yellow. The face is tomentose, except for the tubercle. The eyes are bare. Males are holoptic, females dichoptic. In males, the frons is yellow and tomentose on the basal half adjacent to the eyes. In females, the front is yellow, usually centrally darkened centrally, and covered with tomentum except for the area adjacent to the lunule. Frontal hairs are black. The antennae are simple and yellow, with the dorsal part of the postpedicel darkened. The arista is dark brown.</p>
<p>The scutum is black and largely covered with tomentum, which is especially prominent on the notopleuron and along three central anterior-poserior vittae. Scutal hairs are long and yellow. The scutellum is yellow and bears long black hairs, except along the anterior margin and on the scutellar fringe. The pleura are black and largely covered with tomentum, giving the general appearance of a light grey coloration, except ventrally. Pleural hairs are long and yellow. The metasternum is hairy.</p>
<p>The legs are simple and yellow, typically darkened dorsally on the posterior tibiae and tarsomeres. Leg hairs are long on the femora and shorter on the tibiae and tarsomeres. Hairs are yellow on the fore and mid legs; on the hind legs, hairs are yellow on the coxae, trochanters and basal half of femora, and black on the dorsal part of the remaining portions. The wings are hyaline and completely covered with microtrichia, except for small bare areas on cells bm and br. The halteres are yellow. No long hairs are present on the dorsal surface of the calyptres.</p>
<p>The abdomen is slightly oval. Tergite 1 is black, or black with a yellow anterior margin. Tergite 2 is yellow, with a black posterior margin and a central spot in the proximal half, generally expanded medially; this spot may merge with the black posterior margin. Tergites 3 and 4 are particularly distinctive: anteriorly, there is a yellow band followed by a black one, which in lighter forms may be reduced to two simple spots. This is followed by a broad yellow band and a black posterior margin; tergite 4 may also bear a very narrow yellow band along the posterior edge. Tergite 5 is entirely yellow or yellow with a central black spot. Hairs on tergites 1 and 2 are yellow, although black hairs may be present along the posterior margin. On the following tergites, the hairs are predominantly black. The tergites are unmarginated. Sternites are yellow with a central black vitta, which may be faint or indistinct. Sternite hairs are yellow, with black hairs present on the terminal sternites.</p>
<p>Abdominal coloration in <i>E. balteatus</i> is highly variable and influenced by several factors, particularly the temperature during larval development. As a result, individuals may range from nearly entirely melanistic forms to others in which the black portions of the abdomen are greatly reduced.</p>
<p>In males, the epandrium is trapezoidal; the hypandrium is widened posteriorly to the point of taking on a triangular shape.enlventrally rounded. The surstyli are short, almost flat, apically tapered. The hypandrium lacks a ligula and bears a small postgonite, ventrally serrated. The cerci are oval, clearly longer than larger, and bear long hairs. The basiphallus is slightly compressed and distinctly longer than wide. The distiphallus is also slightly compressed and apically as wide as at its base.</p>
`,
    biology: `The larvae of the genus are zoophagous. The larvae are oval in cross-section, translucent, with whitish fat bodies surrounding the hindgut and often very prominent red Malpighian tubules. The larva of <i>E. batleatus</i> is among the most polyphagous, reported to feed on a very wide range of aphid species. In the past, it has also been reared for mass releases in agroecosystems, especially in greenhouses. Although primarily reported as a predator of aphids, the larvae can also prey on other arthropods, especially soft-bodied ones (e.g., lepidopteran larvae, other syrphid larvae, springtails). Larvae can be found on herbaceous plants, shrubs, and trees, including cultivated ones. The adults are ubiquitous and can be found almost in all habitats, even if they usually preferred woodlands, including urban parks and orchards. Episyrphus balteatus is polyvoltine, and it can overwinter both as adults and larvae. `,
    biodiversity: `The genus <i>Episyrphus</i> includes 19 species (Evenhuis & Pape, 2025), mainly distributed in the Afrotropical and Oriental regions. Only two species occur in the Palearctic region, of which <i>E. balteatus</i> is the only one present in Europe, where it is widely distributed (Reverté et al., 2023).`,
    italianBiodiversity: `<i>Episyrphus balteatus</i> is one of the most common species in the Italian fauna; it has been recorded throughout the national territory, including the islands.`,
    references: [
"Coe, R.L. (1953). Diptera: Syrphidae. Pt. 1, In: Royal Entomological Society of London, Handbooks for the identification of British insects. Vol. 10: Cyclorrhapa. London, 98 pp.",
"Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.",
"Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href=\"http://diptera.org/\" target=\"_blank\">http://diptera.org/</a> [accessed on 25.08.2025]",
"Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.",
"Matsumura, S. Adachi, J. (1917). Synopsis of the economic Syrphidae of Japan. (Pt III). Entomological Magazine, Kyoto 3: 14-46.",
"Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 2023, 48: 250-277. <a href=\"https://doi.org/10.1111/syen.12573\" target=\"_blank\">https://doi.org/10.1111/syen.12573</a>",
"Mengual, X., Ståhls, G., Láska, P., Mazánek, L., & Rojo, S. (2018). Molecular phylogenetics of the predatory lineage of flower flies <i>Eupeodes</i>–<i>Scaeva</i> (Diptera: Syrphidae), with the description of the Neotropical genus <i>Austroscaeva</i> gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56(2), 148–169. <a href=\"https://doi.org/10.1111/jzs.12212\" target=\"_blank\">https://doi.org/10.1111/jzs.12212</a>",
"Mengual, X., Ståhls, G. & Rojo, S. (2008) First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href=\"https://doi.org/10.1111/j.1096-0031.2008.00200.x\" target=\"_blank\">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>",
"Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.",
"Séguy, E. (1961). Diptères Syrphides. Faune de France, vol. 64. Fédération Française des Sociétés de Sciences Naturelles, Paris. 460 pp.",
"Thompson, F. C., Vockeroth, J. R. (1989). Family Syrphidae. In: Evenhuis, N. L. (Ed.), Catalog of the Diptera of the Australasian and Oceanian Regions, pp. 437–458. Honolulu: Bishop Museum Press & E. J. Brill.",
"Veen, van M.P. (2004). Hoverflies of Northwest Europe. Identification keys to the Syrphidae. KNNV Publishing, 254 pp."
]
}


]
