export default [
  {
    taxonName: 'Dasysyrphus',
    author: 'Enderlein, 1938',
    url: '/otus/950163/overview',
    keyUrl: '',
    introduction: `Enderlein (1938) introduced <i>Dasysyrphus</i> as a subgenus of <i>Syrphus</i>. It was not recognized as a valid genus until the revisions by Hippa (1968) and Vockeroth (1969). The latter author proposed a close relationship between <i>Dasysyrphus</i> and <i>Notosyrphus</i>, despite differences in the structure of the male genitalia. However, this relationship has not been supported by recent molecular data (e.g., Mengual et al., 2015, 2018). Based on molecular evidence, Mengual et al. (2018) suggested a close relationship between <i>Dasysyrphus</i> and <i>Melangyna</i>.`,
    diagnosis: `Within Syrphinae, <i>Dasysyrphus</i> species can be readily separated from all other genera by the following combination of characters: yellow face and scutellum; hairy eyes; absence of yellow bands on scutum; anterior part of the anepisternum without long hairs; marginated abdomen; metasternum bare; black abdomen with yellow markings; abdominal markings usually separated and constricted medially; R4+5 without loop. `,
    description: `
      <p>The face is yellow with a central black stripe extending from the base of the antennae to the oral margin (absent in <i>D. hilaris</i>). The oral margin is usually black, though it may be entirely yellow in rare cases (e.g., <i>D. albostriatus</i>). The eyes are densely pilose. Males are holoptic, females dichoptic. The frons is black, though it may be yellow around the antennae in some species (e.g., <i>D. albostriatus</i>). Antennae are simple and black. The frons is shiny, with variable tomentose markings.</p>
      
      <p>The scutum is black and glossy, bearing two tomentose vittae on its anterior half (four vittae occur only in <i>D. eggeri</i>), although these are distinctly visible only in <i>D. albostriatus</i> and <i>D. eggeri</i>. The scutal hairs are long and range from entirely yellow to a mix of black and yellow. The scutellum is yellow and bears long hairs, ranging from completely black to predominantly yellow with some interspersed black hairs. The pleura are entirely black and shiny, with well-developed tomentose areas on the posterior part of the anepisternum and the dorsal side of the katepisternum in some species. The pleural hairs are long and yellow. The metasternum is bare.</p>
        
      <p>Legs are simple and predominantly yellow, with black areas variably present on the femora and hind tibiae depending on the species. The leg hairs are long, either yellow or mixed black and yellow. Wings are hyaline with a distinct black pterostigma and are almost entirely covered with microtrichia. The abdomen is oval and marginated, with yellow markings present on tergites 2–5. The markings are usually separated but may be medially confluent in <i>D. trincinctus</i> and occasionally in <i>D. albostriatus</i>. The yellow markings may or may not connect to the lateral margins of the abdomen. Sternites are yellow with a centrally developed black area of varying extent.</p>
        
      <p>In males, the epandrium is trapezoidal, with the hypandrium rounded ventrally. Surstyli are triangular and apically narrowed. Cerci are oval and bear long hairs. The postgonite exhibits variable morphology. The distiphallus is elongate and distally enlarged, except in <i>D. albostriatus</i> and <i>D. eggeri</i>.</p>    
    `,
    biology: `The larvae of the genus are zoophagous. Based on the limited available data, they feed on aphids, as well as a wide variety of other insect larvae (e.g., sawflies, flies, lepidopterans). Larvae have predominantly been found in association with trees, and more rarely on shrubs and herbaceous plants. Adults are typically found in woodland habitats, including both coniferous and deciduous forests. Most species are univoltine, with the exception of <i>D. albostriatus</i> and <i>D. tricinctus</i>, which are bivoltine. Only <i>D. albostriatus</i> and <i>D. friulensis</i> have been recorded as migratory species.`,
    biodiversity: `Fifty species have been described (Evenhuis and Pape, 2025), most of which originate from the Holarctic region. Only a few species (less than ten) are known from the Oriental region. The genus is absent from Australia and likely from South America as well. Thirty-one species are known from the Palaearctic region, thirteen of which have been reported from Europe (Reverté et al., 2023). Vockeroth (1969) divided the genus into four species groups. Locke & Skevington (2013) revised the Nearctic fauna and, based on morphological and molecular analyses, proposed four species groups: the <i>D. albostriatus</i>, <i>D. pinastri</i>, <i>D. tricinctus</i>, and <i>D. venustus`,
    italianBiodiversity: `
      <p>In Italy eleven species of <i>Daysyrphus</i> have been recorded, most of which occur in mountainous regions. Only <I>D</I>. <i>albostriatus</i>, <I>D</I>. <i>pinastri</i>, <I>D</I>. <i>tricinctus</i> and <I>D</I>. <i>venustus</i> have been reported from Central and Southern Italy. <I>D</I>. <i>albostriatus</i> and <I>D</I>. <i>tricinctus</i> are the only species known to occur in Sicily, while no records exist for Sardinia. In Northern Italy, all species are known to occur, although only <i>D. albostriatus</i> has been documented from the Padania Plain.</p>
        
      <p>For species-level identification, European keys may be used, although they remain incomplete. For instance, van Veen (2004) does not include <i>D. postclaviger</i> and <i>D. neovenustus</i>; Bartsch (2009) omits <i>D. lenensis</i> and <i>D. neovenustus</i>; and Bot & De Meutter (2023) exclude <i>D. eggeri</i> and <i>D. postclaviger</i></p>
    `
  }
]
