// GBIF interpreted `typeStatus` values, CamelCase as the occurrence-search API
// expects them (the /enumeration/basic/TypeStatus list is ALL-CAPS and does NOT
// match — `typeStatus=HOLOTYPE` returns 0, `typeStatus=Holotype` works).
//
// Shared by PanelGbifTypeSpecimens (the type-specimen list) and PanelGallery
// (the GBIF type-image fallback tier). One source of truth — keep it here.
export const TYPE_STATUSES = [
  'Paratype',
  'Holotype',
  'Type',
  'Isotype',
  'Syntype',
  'OriginalMaterial',
  'Lectotype',
  'Isolectotype',
  'Paralectotype',
  'Isosyntype',
  'Plastoisotype',
  'Plastoneotype',
  'Exsyntype',
  'Exneotype',
  'Exlectotype',
  'Exepitype',
  'Plastolectotype',
  'Exparatype',
  'Allolectotype',
  'Exisotype',
  'Exholotype',
  'Plastosyntype',
  'Clonotype',
  'SupplementaryType',
  'Plastoparatype',
  'Metatype',
  'Hapantotype',
  'Isoepitype',
  'Plastotype',
  'Plastoholotype',
  'Paraneotype',
  'Extype',
  'Alloneotype',
  'Isoparatype',
  'Paratopotype',
  'Epitype',
  'Plesiotype',
  'Isoneotype',
  'SecondaryType',
  'TypeStrain',
  'TypeSeries',
  'Homeotype',
  'Neotype',
  'Cotype',
  'Topotype',
  'Allotype',
  'Hypotype',
  'Iconotype'
]
