  const Epistrophella = {
    taxonName: 'Epistrophella',
    author: 'Dušek & Láska, 1967',
    url: '/otus/985203/overview',
    keyUrl: '',
    keyUrlEN: '',
    numSpecies: '4',
    numSpeciesIta: '2',
    distribution: ['Nearctic', 'Palearctic'],
    introduction: `<p>The genus <i>Epistrophella</i> was introduced by Duśek & Láska (1967) to include the single species <i>Syrphus</i> <i>euchroma</i> Kowarz, 1885 and was considered the genus closely related to <i>Epistrophe</i> Walker, 1852. Most authors (e.g. Vockeroth, 1969; Peck, 1988; van Veen, 2004; Bertollo and Sommaggio, 2012) treated <i>Epistrophella</i> as a subgenus of <i>Epistrophe</i>. Based on larval characteristics, Rotheray and Gilbert (1989) confirmed Hippa's (1968) position, which included <i>E. euchroma</i> in the genus <i>Meligramma</i>. This classification was later followed by Speight (2020). Subsequent authors added species to the genus <i>Epistrophella</i>, notably <i>E. emarginata</i> (Say, 1823) and <i>E. horishama</i> (Matsumura, 1917) by Vockeroth (1969), and <i>E. coronata</i> (Rondani, 1957) by Doczkal and Vujić (1998). However, these species exhibit significant differences compared to <i>E. euchroma</i>, and therefore their actual assignment to the genus <i>Epistrophella</i> remains doubtful (Doczkal and Vujić, 1998; Speight, 2020). Recent molecular studies, based on the type species <I>E</I>. <i>euchroma</i>, have confirmed the validity of <i>Epistrophella </i>as a distinct genus (Mengual et al., 2008, 2018, 2023), regarded as the outgroup to the <i>Epistrophe</i> + <i>Afrosyrphus</i> clade (Mengual et al., 2023) and phylogenetically separated from <i>Meligramma</i>.</p>`,
    diagnosis: `The few species of the genus <i>Epistrophella</i> closely resemble those of <i>Epistrophe</i>, with which they share the following characteristics: the calypters are hairless on the upper part, the metasternum is bare, the face is yellow with black oral margin, the eyes are bare, the wings have no spots, and vein R4+5 is straight. However, they can be distinguished from <i>Epistrophe</i> by their abdomen with parallel margins (oval in <i>Epistrophe</i> and in <i>Epistrophella coronata</i>) and unmarginated sides (whereas <i>Epistrophe</i> typically shows marginal lines at least on tergites 3 and 4). Additionally, the abdomen displays separate yellow spots (generally fused in <i>Epistrophe</i>) and more prominent yellow vittae on the mesonotum (absent or barely visible in <i>Epistrophe</i>). <i>Epistrophella euchroma</i> may be confused with the genus <i>Meligramma</i>, but it differs by having abdominal spots separated from the lateral margin and a black oral margin, whereas in <i>Meligramma</i> the abdominal spots merge with the oral margin and/or the face is entirely yellow.`,
    description: `
<p>The face is yellow with a black oral margin; facial hairs are yellow. The eyes are bare. Males are holoptic, females dichoptic. The frons is black - entirely tomentose in males, with central tomentose spots in females. Frontal hairs are black or a mix of yellow and black. The antennae are simple and may be entirely black (<i>E. coronata</i>) or yellowish (<i>E. euchroma</i>).</p>
<p>The scutum is black and shiny, with yellow along the lateral margins. Scutal hairs are long and yellow. The scutellum is yellow, with black restricted to the anterior lateral angles, and bears long yellow hairs. The pleura are black and largely covered with tomentum; yellow spots may be present on the proepimeron, posterior anepisternum, dorsally on the katepisternum, katepimeron and katatergum. Pleural hairs are long, apically wavy and yellow. The metasternum is bare.</p>
<p>The legs are simple and yellow, with black spots on the femora, usually more developed on the hind femora. Leg hairs are long on the femora and shorter on tibiae and tarsomeres. Hairs are yellow on the front and middle legs (with a few black hairs possibly present on the tibiae); hairs on the hind legs are yellow on the coxae, trochanters and basal half of femora, and black on the remaining portions. The wings are hyaline and completely covered with microtrichia, except for small bare areas on cells bm and br. The halteres are yellow. No long hairs are present on the dorsal surface of the calyptres.</p>
<p>The abdomen has parallel margins on <I>E</I>. <i>euchroma</i>, and is more oval in <I>E</I>. <i>coronata</i>. It is black with yellow sport, which are separated from the lateral margins. In <I>E.</I> <i>coronata,</i> the spots are present only on tergites 2 and 3. Tergite hairs are yellow, with black hairs along the posterior margins. The tergites are unmarginated. Sternites are yellow with black lateral margins. Sternite hairs are yellow, with black hairs present on the terminal sternites.</p> 
<p>In males, the epandrium is trapezoidal, and the hypandrium is ventrally rounded. The surstyli are short, apically tapered. The hypandrium bears a consistently present lingula, which is broad and well-developed, though shorter than the postgonites. The postgonites are small and nearly square. The cerci are oval and bear long hairs. The basiphallus is strongly laterally compressed, being much higher than long, and bears small teeth at its base. The distiphallus is long, angular and bears numerous setae on its ventral-apical portion.</p>
`,
    biology: `The larvae of the genus are zoophagous. They exhibit pronounced dorsal flattening, resulting in a distinctly flattened body shape. The larvae feed on aphids on trees and shrubs (<i>Euonymus, Prunus)</i>, including trees in orchard. Adults are typically found in deciduous woodland habitats; <i>E. euchroma</i> can also be found in orchards. Epistrophella species overwinter in the soil, as larvae. All species are univoltine, with adults emerging early in spring. No species within the genus is migratory.`,
    biodiversity: `Evenhuis & Pape, 2025 recorded only four species in the genus Epistrophella. All species are Holoarctic, with three species in the Palaearctic region and only one in the Nearctic regione. Two species have been recorded in Europe (Reverté et al., 2023). `,
    italianBiodiversity: `Both European species are present in Italy. <i>Epistrophella euchroma</i> is the most common, occurring only on mailand; some records of this species are from the Alps while only two records from Central and Southern Italy are available. <i>Epistrophella coronata</i> is very rare; this species has been described by Rondani (1857) and this is the only record for Italy. Doczkal and Vujić (1998) provide a useful comparison between the two species.`,
    references: [
"Bertollo, S., Sommaggio, D. (2012). Riconoscere i Sirfidi: la chiave dicotomica ai generi italiani. Quaderni Stazione di Ecologia Museo civico di Storia Naturale di Ferrara, 20: 101-145.",  
"Doczkal, D., Vujic, A. (1998) Redescription of <i>Epistrophella coronata</i> (Rondani, 1857), stat.rest., comb.nov., with first description of the male and notes on the generic assignment. Volucella, 3: 51-62.",  
"Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.",  
"Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href=\"http://diptera.org/\" target=\"_blank\">http://diptera.org/</a> [accessed on 25.08.2025].",  
"Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.",  
"Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 48: 250-277. <a href=\"https://doi.org/10.1111/syen.12573\" target=\"_blank\">https://doi.org/10.1111/syen.12573</a>.",  
"Mengual, X., Ståhls, G., Láska, P., Mazánek, L., & Rojo, S. (2018). Molecular phylogenetics of the predatory lineage of flower flies <i>Eupeodes</i>–<i>Scaeva</i> (Diptera: Syrphidae), with the description of the Neotropical genus <i>Austroscaeva</i> gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56(2), 148–169. <a href=\"https://doi.org/10.1111/jzs.12212\" target=\"_blank\">https://doi.org/10.1111/jzs.12212</a>.",  
"Mengual, X., Ståhls, G. & Rojo, S. (2008) First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href=\"https://doi.org/10.1111/j.1096-0031.2008.00200.x\" target=\"_blank\">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>.",  
"Peck, L.V. (1988) Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.",  
"Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.",  
"Rotheray, G.E., Gilbert, F.S. (1989). The phylogeny and systematics of European predaceous Syrphidae (Diptera) based on larval and puparial stages. Zoological Journal of the Linnean Society, 95: 29-70.",  
"Speight, M.C.D. (2020). Species accounts of European Syrphidae, 2020. Syrph the Net, the database of European Syrphidae (Diptera), vol. 104, 314 pp., Syrph the Net publications, Dublin.",  
"Veen, van M.P. (2004). Hoverflies of Northwest Europe. Identification keys to the Syrphidae. KNNV Publishing, 254 pp.",  
"Vockeroth, J.R. (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176."
]
};

export default Epistrophella;