const Episyrphus = {
  otuId: 985428,
  taxonName: 'Episyrphus',
  author: 'Matsumura, 1917',
  url: '/otus/985428/overview',
  keyUrl: '',
  keyUrlEN: '',
  numSpecies: '19',
  numSpeciesIta: '1',
  distribution: ['Afrotropical', 'Indomalayan', 'Palearctic'],
  introduction: `<p>Matsumura and Adachi (1917) introduced the genus <i>Episyrphus</i>, designating the newly described species <i>Episyrphus fallaciosus</i> Matsumura, 1917 (a junior synonym of <i>Episyrphus balteatus</i> (De Geer, 1776)), as the type species. The genus was subsequently regarded as a junior synonym of <i>Syrphus</i> (e.g. Coe, 1953). Seguy (1961) treated <i>Episyrphus</i> as a valid genus, although he included species that are now considered to belong to <i>Melangyna</i> Verrall, 1901, <i>Meliscaeva</i> Frey, 1946 and <i>Epistrophella</i> Duśek & Láska, 1967. It was only in the late 1960 that the genus was properly defined (Duśek & Láska, 1967; Hippa. 1968; Vockeroth, 1969). Currently, the genus is divided into two subgenera: <i>Asiobaccha</i> Violovitsh, 1976 and <i>Episyrphus</i> s.s. (Thompson and Vockeroth 1989). Species within <i>Episyrphus</i> are morphologically similar to those of <i>Meliscaeva</i>, and some authors (e.g. van Veen, 2004) have included both under <i>Episyrphus</i>. Recent molecular studies have confirmed the strong phylogenetic relationship among <i>Episyrphus</i> (<i>Episyrphus</i>), <i>Episyrphus</i> (<i>Asiobaccha</i>) and <i>Meliscaeva</i>, with <i>Meliscaeva</i> as the outgroup of the other two taxa (Mengual et al., 2008, 2018, 2023).</p>`,
  diagnosis: `The species of the genera <i>Episyrphus</i> and <i>Meliscaeva</i> can be readily distinguished from all other Syrphinae by the combination of two morphological characters: the presence of hairs on the anterior part of the anepisternum and the sclerotized setal bases along the wing margin, which give the margin  the appearance of a series of black spots. <i>Episyrphus</i> can be separated from <i>Meliscaeva</i> by the presence of a tuft of pile beneath the spiracle of the metepimeron. However, in the Western Palaearctic region, the only species of <i>Episyrphus</i> present (<I>E</I>. <i>balteatus</i>) is easily recognized by its distinctive abdominal pattern, featuring a double yellow band on each tergites 3 and 4.`,
  description: `
<p>The face is enterely yellow, including the oral margin; facial hairs are yellow. The face is tomentose, except for the tubercle. The eyes are bare. Males are holoptic, females dichoptic. In males, the frons is yellow and tomentose on the basal half adjacent to the eyes. In females, the front is yellow, usually centrally darkened centrally, and covered with tomentum except for the area adjacent to the lunule. Frontal hairs are black. The antennae are simple and yellow, with the dorsal part of the postpedicel darkened. The arista is dark brown.</p>
<p>The scutum is black and largely covered with tomentum, which is especially prominent on the notopleuron and along three central anterior-poserior vittae. Scutal hairs are long and yellow. The scutellum is yellow and bears long black hairs, except along the anterior margin and on the scutellar fringe. The pleura are black and largely covered with tomentum, giving the general appearance of a light grey coloration, except ventrally. Pleural hairs are long and yellow. The metasternum is hairy.</p>
<p>The legs are simple and yellow, typically darkened dorsally on the posterior tibiae and tarsomeres. Leg hairs are long on the femora and shorter on the tibiae and tarsomeres. Hairs are yellow on the fore and mid legs; on the hind legs, hairs are yellow on the coxae, trochanters and basal half of femora, and black on the dorsal part of the remaining portions. The wings are hyaline and completely covered with microtrichia, except for small bare areas on cells bm and br. The halteres are yellow. No long hairs are present on the dorsal surface of the calyptres.</p>
<p>The abdomen is slightly oval. Tergite 1 is black, or black with a yellow anterior margin. Tergite 2 is yellow, with a black posterior margin and a central spot in the proximal half, generally expanded medially; this spot may merge with the black posterior margin. Tergites 3 and 4 are particularly distinctive: anteriorly, there is a yellow band followed by a black one, which in lighter forms may be reduced to two simple spots. This is followed by a broad yellow band and a black posterior margin; tergite 4 may also bear a very narrow yellow band along the posterior edge. Tergite 5 is entirely yellow or yellow with a central black spot. Hairs on tergites 1 and 2 are yellow, although black hairs may be present along the posterior margin. On the following tergites, the hairs are predominantly black. The tergites are unmarginated. Sternites are yellow with a central black vitta, which may be faint or indistinct. Sternite hairs are yellow, with black hairs present on the terminal sternites.</p>
<p>Abdominal coloration in <i>E. balteatus</i> is highly variable and influenced by several factors, particularly the temperature during larval development. As a result, individuals may range from nearly entirely melanistic forms to others in which the black portions of the abdomen are greatly reduced.</p>
<p>In males, the epandrium is trapezoidal; the hypandrium is widened posteriorly to the point of taking on a triangular shape.enlventrally rounded. The surstyli are short, almost flat, apically tapered. The hypandrium lacks a ligula and bears a small postgonite, ventrally serrated. The cerci are oval, clearly longer than larger, and bear long hairs. The basiphallus is slightly compressed and distinctly longer than wide. The distiphallus is also slightly compressed and apically as wide as at its base.</p>
`,
  biology: `The larvae of the genus are zoophagous. The larvae are oval in cross-section, translucent, with whitish fat bodies surrounding the hindgut and often very prominent red Malpighian tubules. The larva of <i>E. batleatus</i> is among the most polyphagous, reported to feed on a very wide range of aphid species. In the past, it has also been reared for mass releases in agroecosystems, especially in greenhouses. Although primarily reported as a predator of aphids, the larvae can also prey on other arthropods, especially soft-bodied ones (e.g., lepidopteran larvae, other syrphid larvae, springtails). Larvae can be found on herbaceous plants, shrubs, and trees, including cultivated ones. The adults are ubiquitous and can be found almost in all habitats, even if they usually preferred woodlands, including urban parks and orchards. Episyrphus balteatus is polyvoltine, and it can overwinter both as adults and larvae. `,
  biodiversity: `The genus <i>Episyrphus</i> includes 19 species (Evenhuis & Pape, 2025), mainly distributed in the Afrotropical and Indomalayan regions. Only two species occur in the Palearctic region, of which <i>E. balteatus</i> is the only one present in Europe, where it is widely distributed (Reverté et al., 2023).`,
  italianBiodiversity: `<i>Episyrphus balteatus</i> is one of the most common species in the Italian fauna; it has been recorded throughout the national territory, including the islands.`,
  references: [
    'Coe, R.L. (1953). Diptera: Syrphidae. Pt. 1, In: Royal Entomological Society of London, Handbooks for the identification of British insects. Vol. 10: Cyclorrhapa. London, 98 pp.',
    'Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.',
    'Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href="http://diptera.org/" target="_blank">http://diptera.org/</a> [accessed on 25.08.2025]',
    'Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.',
    'Matsumura, S. Adachi, J. (1917). Synopsis of the economic Syrphidae of Japan. (Pt III). Entomological Magazine, Kyoto 3: 14-46.',
    'Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 2023, 48: 250-277. <a href="https://doi.org/10.1111/syen.12573" target="_blank">https://doi.org/10.1111/syen.12573</a>',
    'Mengual, X., Ståhls, G., Láska, P., Mazánek, L., & Rojo, S. (2018). Molecular phylogenetics of the predatory lineage of flower flies <i>Eupeodes</i>–<i>Scaeva</i> (Diptera: Syrphidae), with the description of the Neotropical genus <i>Austroscaeva</i> gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56(2), 148–169. <a href="https://doi.org/10.1111/jzs.12212" target="_blank">https://doi.org/10.1111/jzs.12212</a>',
    'Mengual, X., Ståhls, G. & Rojo, S. (2008) First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href="https://doi.org/10.1111/j.1096-0031.2008.00200.x" target="_blank">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>',
    'Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.',
    'Séguy, E. (1961). Diptères Syrphides. Faune de France, vol. 64. Fédération Française des Sociétés de Sciences Naturelles, Paris. 460 pp.',
    'Thompson, F. C., Vockeroth, J. R. (1989). Family Syrphidae. In: Evenhuis, N. L. (Ed.), Catalog of the Diptera of the Australasian and Oceanian Regions, pp. 437–458. Honolulu: Bishop Museum Press & E. J. Brill.',
    'Veen, van M.P. (2004). Hoverflies of Northwest Europe. Identification keys to the Syrphidae. KNNV Publishing, 254 pp.'
  ]
}

export default Episyrphus
