  const Epistrophe = {
    taxonName: 'Epistrophe',
    author: 'Walker, 1852',
    url: '/otus/950604/overview',
    keyUrl: '/keys/2958',
    keyUrlEN: '/keys/2843',
    numSpecies: '53',
    numSpeciesIta: '7',
    distribution: ['Nearctic', 'Palearctic', 'Oriental'],
    introduction: `<p>Although the genus <i>Epistrophe</i> was introduced by Walker (1852), it has traditionally been regarded as a junior synonym of <i>Syrphus</i> Fabriucius, 1775 (e.g. Verrall, 1901; Bezzi & Stein, 1907). Later authors recognized <i>Epistrophe</i> as a valid genus, albeit in a broader sense than it is understood today. For example, Sack (1930) included within <i>Epistrophe</i> several species that are now classified under <i>Parasyrphus</i>, <i>Episyrphus</i>, <i>Meligramma</i> and <i>Melangyna</i>.</p>
<p>It was only through the revision of <i>Syrphus</i> and allied genera—primarily based on male genitalia—that the boundaries of <i>Epistrophe</i> became more clearly defined (Duśek & Láska, 1967; Hippa, 1968; Vockeroth, 1969). The genus is often divided into two subgenera: <i>Epistrophe</i> and <i>Epistrophella</i> (Peck, 1988; van Veen, 2004; Bertollo & Sommaggio, 2012). Recent molecular studies have not only confirmed the validity of <i>Epistrophe</i> as a monophyletic group but have also highlighted that <i>Epistrophella</i> should be considered a distinct genus (Mengual et al., 2008; 2023). <i>Epistrophe</i> undoubtedly belongs to the tribe Syrphini, but its phylogenetic position remains unresolved. Mengual et al. (2008) proposed a clade consisting of (<i>Epistrophe</i> + <i>Chrysotoxum</i>) + (<i>Xanthogramma</i> + <i>Epistrophella</i>). More recently, Mengual et al. (2023) suggested a different arrangement: (<i>Epistrophe</i> + <i>Afrosyrphus</i>) + <i>Epistrophella</i>) + <i>Leucozona</i>.</p>
`,
    diagnosis: `The genus <i>Epistrophe</i> includes morphologically diverse species, characterized by the consistency of male terminalia, particularly in the shape of the surstyli, development of the lingula, and form of the aedeago. The species of this genus are medium to large-sized, generally with broad yellow bands on tergites 3–5. The thorax lacks distinct longitudinal yellow vittae (although some species may show faint vittae); the calypters are hairless on the upper part, the metasternum is bare, the face is entirely yellow, the eyes are bare, the wings have no spots, and vein R4+5 is straight. The abdomen is marginated, at least tergites 4 and 5.`,
    description: `
<p>The face is yellow and covered with yellow hairs. The oral margin may be either yellow or black. The eyes are bare. Males are holoptic, females dichoptic. The frons varies in coloration, ranging from entirely black to entirely yellow, and features extended tomentose areas. The hairs on the frons are also variable, from completely black to completely yellow. The antennae are simple and may be entirely black (e.g., <i>E. glossulariae</i>, <i>E. leiophthalma</i>) or show varying degrees of yellowish coloration on the ventral side (e.g., <i>E. diaphana</i>, <i>E. nitidicollis</i>).</p>
<p>The scutum is black and tomentose, even if in a few species (e.g. <I>E</I>. <i>eligans</i>, <I>E</I>. <i>nitidicollis</i>) it may be shiny. Scutal hairs are long and yellow. The scutellum is yellow and bears long yellow hairs; in few species ((e.g. <I>E</I>. <i>glossulariae</i>) some black hairs may be present along its posterior margin. The pleura are entirely black and largely covered with tomentosity; in <I>E</I>. <i>glossulariae,</i> the dorsal part of keterpisternum and and katepimeron may be yellow. Pleural hairs are long and yellow. The metasternum is bare.</p>
<p>The legs are simple and predominantly yellow, with the tarsomeres of the hind legs being black. In a few species (e.g., <i>E. glossulariae</i>, <i>E. leiophthalma</i>), the bases of the front and middle femora may be black. Leg hairs are long on the femora and shorter on tibiae and taromeres. The hairs are generally yellow, with, on the hind leg, black hairs on the distal portion of the femora and on the tibiae of hind legs; however this varies among species (e.g. entirely yellow in <I>E</I>. <i>leiophthalma</i>).  The wings are hyaline and completely covered with microtrichia, except in some species where cells bm and br may have bare areas. The halteres are yellow. No long hairs are present on the dorsal surface of the calyptres.</p>
<p>Abdominal markings are highly variable among <i>Epistrophe</i> species. The most common pattern consists of two large yellow spots on the second tergite and a yellow band on tergites 3–5. In <i>E. leiophthalma</i>, the abdomen is black with distinct tomentose spots on tergites 2–5. In <i>E. eligans</i>, the yellow bands vary in size, with the band on tergite 3 being larger than those on tergites 4 and 5; in darker specimens, the latter bands may be absent. Tergite hairs are generally yellow, with black hairs present along the posterior margins. The tergites are slightly marginated only on segments 4 and 5. Sternites are usually entirely yellow and bear long yellow hairs; however, this pattern may vary among species, with the posterior sternites being partially or entirely black to varying degrees.</p>
<p>In males, the epandrium is trapezoidal, and the hypandrium is ventrally rounded. The surstyli are short, nearly square, apically truncated. The hypandrium bears a consistently present lingula, which is broad and well-developed, though shorter than the postgonites. The postgonites are long and narrow. The cerci are oval and bear long hairs. The basiphallus is strongly laterally compressed, being much higher than long, and bears two prominent teeth at its base. The distiphallus is slightly longer than the basiphallus.</p>
`,
    biology: `The larvae of the genus are zoophagous. They exhibit pronounced dorsal flattening, resulting in a distinctly flattened body shape. Typically green in color, they are well adapted to preying on aphids found on deciduous trees (reported, for example, on <i>Acer</i>, <i>Prunus</i>, <i>Malus</i>, <i>Sambucus</i>) as well as on tall broad-leaved herbs such as <i>Cichorium</i>. Adults are typically found in deciduous woodland habitats; a few northern European species have also been recorded in coniferous forests. <i>Epistrophe eligans</i> and <I>E</I>. <i>nitidicollis</i> can also be found in anthropized habitat such as hedgerow and urban garden. Most species overwinter in the soil, typically beneath trees. All species are univoltine, with adults emerging early in spring. No species within the genus is migratory.`,
    biodiversity: `Fifty-three species have been described to date (Evenhuis & Pape, 2025). The genus is particularly species-rich in the Eastern Palaearctic region, with more than 20 species described from China in recent publications (Huo et al., 2007; Hao et al., 2012). Only a few species are present in the Nearctic and Oriental regions, while the genus is absent from the Afrotropical and Australian regions. Twelve species have been recorded in Europe (Reverté et al., 2023). Doczkal & Schmid (1994) revised the German fauna of the genus, describing three new species.`,
    italianBiodiversity: `<p>Only 7 of the 12 European species are present in Italy. Among these, <i>E. eligans</i> is the most common, occurring throughout the country, including the major islands. Another widespread species is <i>E. nitidicollis</i>, although no records currently exist for the major islands. The remaining five species are less frequent and are found primarily in northern and central Italy. <i>Epistrophe leiophthalma</i>, <i>E. diaphana</i>, and <i>E. glossulariae</i> are predominantly montane, while the other species are associated with lowland woodlands.</p>
<p>For species identification, the available European keys (e.g., van Veen, 2004; Bot & van de Meutter, 2023) include all Italian species. Particular caution should be exercised when interpreting records predating the work of Doczkal & Schmid (1994), as considerable confusion previously existed within the genus. For example, Italian records of <i>E. ochrostoma</i> are likely erroneous, as this species is native to central and northern Europe.</p>
`,
    references: [
"Bertollo, S., Sommaggio, D. (2012). Riconoscere i Sirfidi: la chiave dicotomica ai generi italiani. Quaderni Stazione di Ecologia Museo civico di Storia Naturale di Ferrara, 20: 101-145.",  
"Bezzi, M., Stein P. (1907). Cyclorrapha Aschiza. Cyclorrapha Schizophora: Schizometopa. In: Becker, T., Bezzi, M., Kertész, K., Stein, P. (eds.): Katalog der palaarktischen Dipteren, Vol. 3. Budapest. Pp. 1-188.",  
"Bot, S., van de Meutter, F. (2023). Hoverflies of Britain and North-west Europe. A photographic guide. Bloomsbury Wildlife, London, 400 pp.",  
"Doczkal, D., Schimd, U. (1994). Drei neue Arten der Gattung <i>Epistrophe</i> (Diptera: Syrphidae), mit einem Bestimmungsschlussel fur der deutschen Arten. Stuttgarter Beiträge zur Naturkunde (A) 507: 1-32.",  
"Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.",  
"Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href=\"http://diptera.org/\" target=\"_blank\">http://diptera.org/</a> [accessed on 25.08.2025].",  
"Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.",  
"Hao, X.L., Huo, K.K., Ren, B.Z. (2012). Two new species of the genus <i>Epistrophe</i> from Jilin Province (Diptera, Syrphidae). Acta Zootaxonomica Sinica 37: 199-202.",  
"Huo, K.K., Ren, G.D., Zheng, Z.M. (2007). Fauna of Syrphidae from Mt. Qinling-Bashan in China (Insecta: Diptera). Beijing Huonzheng., Beijing. 512 pp.",  
"Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 48: 250-277. <a href=\"https://doi.org/10.1111/syen.12573\" target=\"_blank\">https://doi.org/10.1111/syen.12573</a>.",  
"Mengual, X., Ståhls, G. & Rojo, S. (2008). First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href=\"https://doi.org/10.1111/j.1096-0031.2008.00200.x\" target=\"_blank\">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>.",  
"Peck, L.V. (1988). Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.",  
"Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775.",  
"Sack, P. (1930). 31. Syrphidae [part]. In: Lindner, E. (ed.): Die Fliegen der Palaearktischen Region 4(6): 177-240.",  
"Veen, van M.P. (2004). Hoverflies of Northwest Europe. Identification keys to the Syrphidae. KNNV Publishing, 254 pp.",  
"Verrall, G.H. (1901). British flies. Vol. VIII, Platypezidae, Pipunculidae and Syrphidae of Great Britain. Gurney & Jackson, London, 691 pp.",  
"Vockeroth, J.R. (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176."
]
};

export default Epistrophe;