const Eupeodes = {
  otuId: 1024692,
  taxonName: 'Eupeodes',
  author: 'Osten-Sacken, 1877',
  url: '/otus/1024692/overview',
  keyUrl: '/keys/3820',
  keyUrlEN: '',
  numSpecies: '85',
  numSpeciesIta: '12',
  distribution: ['Afrotropical', 'Australasian', 'Indomalayan', 'Nearctic', 'Neotropical', 'Palearctic'],
  introduction: `<p>The genus <i>Eupeodes</i> was established by Osten Sacken (1877) for the North American species <i>Eupeodes volucris</i> Osten Sacken, 1877. The genus was regarded as valid by subsequent authors, but applied only to the nominal species (Williston, 1886, 1908; Metcalf, 1916). Matsumura later introduced the genus <i>Metasyrphus</i> for the Palaearctic species <i>Syrphus corollae</i> Fabricius, 1794 (Matsumura and Adachi, 1917). The genus was not adopted by later European authors (e.g. Sack, 1930; Séguy, 1961), whereas Fluke (1952), for example, treated it as valid at least for the American species.</p>
<p>Matsumura, in the same year, introduced the subgenus <i>Macrosyrphus</i> as a subgenus of <i>Syrphus</i>, designating <i>Syrphus okinawae</i> Matsumura, 1917 as the type species (Matsumura and Adachi, 1917). The subgenus was not adopted by subsequent authors (see Hippa, 1968), whereas Vockeroth (1969) regarded it as an unrecognized genus. Thompson and Vockeroth (1989) treated <i>Macrosyrphus</i> as a valid subgenus of <i>Eupeodes</i>, including only species from the eastern Palaearctic region.</p>
<p>Enderlein (1937) introduced the new genus <i>Posthosyrphus</i> for the North American species <i>Syrphus americanus</i> Wiedemann, 1830. This genus was treated as a synonym of <i>Metasyrphus</i> by Fluke (1952).</p>
<p>In their review of European genera of Syrphinae subfamily, Dušek and Láska (1967) considered <i>Metasyrphus</i> a valid genus and recognized four subgenera within it: <i>Metasyrphus</i> s.s. (type species <i>S. corollae</i>), <i>Posthosyrphus</i> Enderlein, 1938 (type species <i>Syrphus americanus</i>), and the two new subgenera <i>Scaevosyrphus</i> (type species <i>Syrphus lundbecki</i> Soot-Ryen, 1941) and <i>Lapposyrphus</i> (type species <i>Scaeva lappona </i>Zettestedt, 1838).</p>
<p>Hippa (1968) treated <i>Posthosyrphus</i> and <i>Metasyrphus</i> as two separate genera, assigning to the former the species that are today placed in <i>Eupeodes</i>, and restricting the latter to <i>Syrphus corollae</i>. He also retained <i>Lapposyrphus lapponicus</i> within the genus <i>Scaeva</i>. Neither Dušek & Láska (1967) nor Hippa (1968) included <i>Eupeodes volucris</i> in their revisions of <i>Syrphus</i> and related genera.</p>
<p>Vockeroth (1969) regarded <i>Posthosyrphus</i> as a synonym of <i>Metasyrphus</i> and, following Dušek & Láska (1967), retained <i>Lapposyrphus</i> as a subgenus of <i>Metasyrphus</i>. Vockeroth (1969) treated <i>Eupeodes</i> as a separate genus, but only for the species <i>E. volucris</i>. However, he emphasized the considerable similarity between <i>Eupeodes</i> and <i>Metasyrphus</i> in all characters except the male genitalia, suggesting that the genitalia of <i>Eupeodes</i> might represent a highly derived condition of those found in <i>Metasyrphus</i>, in which case the two genera should be united.</p>
<p>Subsequent authors, especially European ones, treated <i>Metasyrphus</i> as a genus separate from <i>Eupeodes</i>, within which they recognized two subgenera (<i>Metasyrphus</i> s.s. and <i>Lapposyrphus</i>) (e.g. Dušek and Láska, 1973, 1976; Stubbs and Falk, 1983; Peck, 1988). Other authors, mainly North American, instead regarded <i>Metasyrphus</i> as a synonym of <i>Eupeodes</i>, which therefore included two subgenera (<i>Eupeodes</i> s.s. and <i>Lapposyrphus</i>) (e.g. Vockeroth and Thompson, 1987; Vockeroth, 1992). From the 1990s onward, however, this latter interpretation has been increasingly adopted also by European authors (e.g. Torp, 1994; van Veen, 2004; Bot and van de Meutter, 2023).</p>
<p>Mengual et al. (2008, 2018, and 2023), based on molecular evidence, confirmed the synonymy of <i>Metasyrphus</i> with <i>Eupeodes</i>, but at the same time recognized <i>Lapposyrphus</i> as a genus distinct from <i>Eupeodes</i> rather than a subgenus of it. Mengual et al. (2018) also confirmed <i>Macrosyrphus</i> as a valid subgenus of Eupeodes including three species. From a phylogenetic perspective, <i>Eupeodes</i> appears to be the outgroup to a broad clade of genera that includes <i>Lapposyrphus</i>, <i>Simosyrphus</i>, <i>Pseudodoros</i>, <i>Ischiodon</i>, <i>Scaeva</i>, <i>Notosyrphus</i>, <i>Austroscaeva</i>, and <i>Dioprosopa</i>, although the phylogenetic relationships among these latter groups are not consistent across the different analyses (Mengual et al., 2008, 2018, 2023).</p>
`, 
diagnosis: `
<p>The genus <i>Eupeodes</i> can be readily distinguished from other genera of the tribe Syrphini (bare humeri; scutellum and/or face at least partly yellow) by the following combination of characters: calypter without dorsal hairs; eyes bare; abdomen with a clearly marginate, at least on tergites 4 and 5; abdominal margin bearing only black hairs from the third tergite onward; notum without yellow vittae along the margin; metasternum hairy; vein R4+5 almost straight. All Italian species have a black abdomen with yellow spots or bands.</p>
<p>The genus is particularly close to <i>Lapposyrphus</i>, from which it can, however, be easily separated by the almost straight R4+5 vein (strongly curved in <i>Lapposyrphus</i>) and by the hairy metasternum (bare in <i>Lapposyrphus</i>). It is also easily distinguished from <i>Epistrophella</i> by the much more evident abdominal margin, the entirely black hairs on the lateral abdominal margin (yellow and black in <i>Epistrophella</i>), and the entirely black notum (with yellow vittae sometimes faint in <i>Epistrophella</i>).</p>
<p>Some large <i>Eupeodes</i> species with reduced microtrichia on the wings (particularly <i>E. lundbecki</i>) may resemble species of the genus <i>Scaeva</i>, but in the latter the eyes are hairy.</p>
`,
  description: `
<p>The face is yellow, usually with a black vittae running dorsoventrally from the oral margin to the facial tubercle; the black vittae may be completely absent only in <I>E</I>. <i>nuba</i> within European fauna. The face is covered with yellow hairs, except very few cases (e.g. the male of <I>E</I>. <i>nielseni</i>). The oral margin is yellow, becoming black only under centrally and along the margin (completely yellow in E. nuba). The eyes are bare. Males are holoptic, females dichoptic. In males the frons is yellow, with tomentum present on the proximal half. In females the posterior part of the frons is black (the extent of which may be an important taxonomic feature); tomentum spots are usually present near the eyes, but in some species (e.g. <I>E</I>. <i>tirolensis</i>, <I>E</I>. <i>latifasciatus</i>) they may be completely absent.  The hairs on the frons are black. The antennae are simple and range in colour from entirely black to reddish. The occiput is whitish due to extensive tomentum, eventually absent behind the ocellar triangle; the dorsal width of the occiput dorsally has been used as a taxonomic character in male identification.</p>
<p>The scutum is black and shiny; tomentum may be present in the central part of the scutum. Scutal hairs are long and yellow. The scutellum is yellow, with small black spots at the anterior angles. The hairs of the scutellum range from completely yellow (e.g. <I>E</I>. <i>corollae</i>, <I>E</I>. <i>latifasciatus</i>) to mostly black (e.g. <I>E</I>. <i>nitens</i>, <I>E</I>. <i>nielseni</i>. The pleura are entirely black and largely covered with tomentum (largely reduced  in a few species, e.g. <I>E</I>. <i>nitens</i>). Pleural hairs are long and yellow. The metasternum is hairy.</p>
<p>The legs are simple; the coxae and trochanters are black, the tibiae are yellow, and the tarsomeres are brown. The femora are variable: in a few species they are entirely yellow, but more commonly they bear a more or less extended black basal portion. The fore and mid legs have short yellow hairs, except on the posterior half of the femora, where the hairs are long and may include (or even be dominated by) black hairs depending on the species. The hairs on the hind legs are short and black, except at the base of the femora, where long yellow hairs are present. The wings are hyaline and completely covered with microtrichia, except for cells bm and br, which bear bare areas, and the alula, where bare patches may occur depending on the species. The halteres are yellow. No long hairs are present on the dorsal surface of the calypters.</p>
<p>The abdomen is clearly marginate. It is black with yellow spots or bands; within the European fauna, only in <i>E. rufipunctatus</i>—recorded exclusively from Iceland—may the yellow abdominal spots be completely absent. The yellow markings are always separated on the second tergite, whereas on tergites 3–5 the spots may be joined to form a band (e.g. in some specimens of <i>E. corollae</i> and <i>E. nitens</i>). Tergite hairs are generally black, except on the yellow spots/bands and on the anterior margin of the second tergite. From the posterior half of the second tergite onwards, the hairs on the lateral margins of the tergites are entirely black. The sternites are yellow, with a more or less extended central black spot (rarely absent). The hairs of the sternites are usually long and yellow, although black hairs may be present from the third sternite onwards.</p>
<p>The male genitalia are extremely variable, particularly in <i>E. volucris</i>. The epandrium is trapezoidal, and the hypandrium is rounded ventrally. The surstyli are long and usually taper apically (shorter in the subgenus <i>Macrosyrphus</i>). The hypandrial lingula is usually absent or short, but it is well developed in the subgenus <i>Macrosyrphus</i>. The postgonites are broader at the base and rounded apically. The cerci are oval and bear long hairs. The basiphallus is strongly laterally compressed and bears two ventral teeth, the apical one usually shorter than the basal one and occasionally completely absent. The distiphallus is long and apically compressed.</p>
`,
  biology:
 'The larvae of the genus are zoophagous. They are sub-cilindrical and well adapted for moving on cylindrical structures. For this reason, aphidophagy on conifer feeding aphids t has been considered the ancestral condition of the genus (e.g. Rotheray, 1994). Some species (e.g. <I>E</I>. <i>nielseni</i>) are specialized predators on conifer aphids, whereas most species exploit a wide range of aphids, mainly on herbaceous plants, including, in a few cases, also root feeding aphids (e.g. <I>E</I>. <i>latifasciatus</i>). Some species (<I>E</I>. <i>corollae</i>, <I>E</I>. <i>americanus</i>) are also common on crops and are widely used in augmentative biological control (Burgio et al., 2025). Adults occur in a broad array of habitats; some species (e.g. <I>E</I>. <i>corollae</i>, <I>E</I>. <i>luniger</i>) are almost ubiquitous, although they prefer open habitats. Other species are more specialized; for example, <I>E</I>. <i>nielseni</i> is typically associated with coniferous forests. Most species overwinter in the herb layer, usually as larvae, and only rarely as pupae (e.g. <I>E</I>. <i>luniger</i>). Most species are bivoltine; species living in areas with short summers (e.g. arctic or montane species) are univoltine (e.g. <I>E</I>. <i>nielseni</i>, <I>E</I>. <i>tirolensis</i>, <I>E</I>. <i>nitens</i>). Species from Mediterranean regions may be polyvoltine (e.g. <I>E</I>. <i>nuba</i>, <I>E</I>. <i>flaviceps</i> and also the widespread <I>E</I>. <i>corollae</i>). Most species are non-migratory, but <I>E</I>. <i>corollae</i>, <I>E</I>. <i>lundbecki</i> and <I>E</I>. <i>luniger</i> are considered as strongly migratory.',
  biodiversity: `
  <p>Eighty five species have been described to date (Evenhuis & Pape, 2026). The genus is almost exclusively distributed in the Northern Hemisphere: only one species has been recorded from the Neotropical region, one from the Afrotropical region, and one from Australian and Indo-Malayan region. The Palaearctic fauna is particularly rich (65 species), especially in its eastern part, with 38 species known only from Japan and China.</p>
  <p>Twenty species have been recorded in Europe, five of which are known only from the northernmost regions—Scandinavia or Iceland (Reverté et al., 2023). Eighteen species are known from the Nearctic fauna, three of which are Holarctic.</p>
  `,
  italianBiodiversity: `
  <p>Twelve of the twenty European species are present in Italy, and three additional species (<i>E. biciki</i>, <i>E. goeldlinii</i> and <i>E. lambecki</i>) may also occur in the country, as they have been recorded from regions bordering Italy.</p>
  <p>Several species—particularly <i>E. corollae</i>, <i>E. luniger</i> and <i>E. latifasciatus</i>—are common and widely distributed across the national territory. Four species (<i>E. tirolensis</i>, <i>E. nielseni</i>, <i>E. nitens</i>, <i>E. lundbecki</i>) are typically montane and occur only in the Alps and/or the northern Apennines. Finally, some species are more closely associated with Mediterranean environments, and their presence is either restricted to southern regions (e.g. <i>E. vandergooti</i>) or they are generally more frequent in central and southern Italy (e.g. <i>E. flaviceps</i>, <i>E. nuba</i>, <i>E. lucasi</i>).</p>
  <p>At present, no identification keys include all Italian species of the genus <i>Eupeodes</i>. Van Veen (2004) is useful, although it does not cover <i>E. flaviceps</i>, <i>E. lucasi</i>, <i>E. nuba</i> or <i>E. vandergooti</i>. Speight and Sarthou (2017) is more comprehensive, but still does not include <i>E. flaviceps</i> or <i>E. vandergooti</i>. Dušek & Láska (1976) include these species, but do not cover taxa described later (e.g. <i>E. lucasi</i>) and use outdated nomenclature (e.g. <i>E. nuba</i> = <i>E. interrupens</i>).</p>
  `,
  references: [
    'Bot, S., van de Meutter, F. (2023). Hoverflies of Britain and North-west Europe. A photographic guide. Bloomsbury Wildlife, London, 400 pp.',
    'Burgio G., Dindo M.L., Pape T., Whitmore D., Sommaggio D. 2025. Diptera as predators in biological control: applications and future perspectives. Bioncontrol, <a href="https://doi.org/10.1007/s10526-024-10281-2" target="_blank">https://doi.org/10.1007/s10526-024-10281-2</a>',
    'Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.',
    'Dušek, J., Láska, P. (1973). Descriptions of five new European species of the genus <i>Metasyrphus</i> (Diptera: Syrphidae), with notes on variation within the species. <i>Acta Entomologica Bohemoslovaca</i>, 70(6): 415–426.',
    'Dušek, J., Láska, P. (1976). European species of <i>Metasyrphus</i>: key, descriptions and notes. <i>Acta Entomologica Bohemoslovaca</i>, 73: 263–282.',
    'Enderlein, G. (1938). Beitrag zur Kenntnis der Syrphiden. Sitzungsberichte der Gesellschaft Naturforschender Freunde Berl. 1937: 192-237',
    'Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href="http://diptera.org/" target="_blank">http://diptera.org/</a> [accessed on 25.08.2025]',
    'Fluke, C.L. (1952). The <i>Metasyrphus</i> species of North America (Diptera: Syrphidae). American Museum Novitates, 1590: 1–27.',
    'Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.',
    'Matsumura, S., Adachi, J. (1917). Synopsis of the economic Syrphidae of Japan. (Pt II). Ent.Mag., Kyoto 2(4): 133-156, pl. 6.',
    'Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 2023, 48: 250-277. <a href="https://doi.org/10.1111/syen.12573" target="_blank">https://doi.org/10.1111/syen.12573</a>',
    'Mengual, X., Ståhls, G., Láska, P., Mazánek, L., Rojo, S. (2018) Molecular phylogenetics of the predatory lineage of flower flies <i>Eupeodes</i>-<i>Scaeva</i> (Diptera: Syrphidae), with the description of the Neotropical genus <i>Austroscaeva</i> gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56: 148-169.',
    'Mengual, X., Ståhls, G. & Rojo, S. (2008) First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href="https://doi.org/10.1111/j.1096-0031.2008.00200.x" target="_blank">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>',
    'Metcalf, C.L. (1916). <i>Syrphidae of Maine</i>. Maine Agricultural Experiment Station, Bulletin 253: 125–169.',
    'Osten Sacken, C.R. (1877). Western Diptera: Descriptions of new genera and species of Diptera from the region west of the Mississippi and especially from California. Bulletin of the United States Geological and Geographical Survey of the Territories, 3: 189-354.',
    'Peck, L.V. (1988) Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.',
    'Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775. ',
    'Rotheray, G.E. (1994) Colour guide to hoverfly larvae (Diptera, Syrphidae) in Britain and Europe. <i>Dipterists Digest</i>, (1993), No.9: 1-156.',
    'Sack, P. (1930). 31. Syrphidae [part]. In: Lindner, E. (ed.): Die Fliegen der Palaearktischen Region 4(6): 177-240.',
    'Speight, M.C.D., Sarthou, J.-P. (2017) StN keys for the identification of the European species of various genera of Syrphidae 2017/. <i>Syrph the Net, the database of European Syrphidae (Diptera)</i>, Vol. 99, 139 pp, Syrph the Net publications, Dublin.',
    'Stubbs, A.E., Falk, S.J. (1983). <i>British hoverflies: an illustrated identification guide</i>. British Entomological and Natural History Society, London, 253 pp.',
    'Thompson, F.C., Vockeroth, J. R. (1989). Family Syrphidae. In N.L. Evenhuis (Ed.), Catalog of the Diptera of the Australasian and Oceanian regions (pp. 437–458). Hawaii: Bishop Museum Special Publication vol. 86. <a href=" https://doi.org/10.5962/bhl.title.49897" target="_blank"> https://doi.org/10.5962/bhl.title.49897/</a>',
    'Torp, E. (1994) Danmarks Svirrefluer (Diptera: Syrphidae). Danmarks Dyreliv, 6: 1-490. Apollo books, Stenstrup.',
    'Veen, van M.P. (2004). Hoverflies of Northwest Europe. Identification keys to the Syrphidae. KNNV Publishing, 254 pp.',
    'Vockeroth, J.R., (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176.',
    'Vockeroth, J.R. (1992). <i>The flower flies of the subfamily Syrphinae of Canada, Alaska, and Greenland (Diptera: Syrphidae).</i> The Insects and Arachnids of Canada, Part 18. Research Branch, Agriculture Canada, Ottawa, 343 pp.',
    'Vockeroth, J.R., Thompson, F.C. (1987). Syrphidae. In: McAlpine, J.F. et al. (eds), <i>Manual of Nearctic Diptera</i>, Volume 2. Agriculture Canada, Research Branch, Ottawa. Monograph No. 28: 713–743.',
    'Williston, S.W. (1886). <i>Synopsis of the families and genera of North American Diptera</i>. Bulletin of the United States National Museum, 31: 1–335.',
    'Williston, S.W. (1908). <i>Synopsis of the North American Syrphidae</i>. Bulletin of the United States National Museum, 31: 1–324.',
 ]
}

export default Eupeodes
