const Fagisyrphus = {
  otuId: 1024824,
  taxonName: 'Fagisyrphus',
  author: 'Dušek and Láska, 1967',
  url: '/otus/1024824/overview',
  keyUrl: '',
  keyUrlEN: '',
  numSpecies: '1',
  numSpeciesIta: '1',
  distribution: ['Palearctic'],
  introduction: `
  <p>Dušek and Láska (1967) introduced the subgenus <i>Lapposyrphus</i> within the genus <i>Metasyrphus</i> Matsumura, 1917 to accommodate the single species <i>Scaeva lapponica</i> Zetterstedt, 1838. Hippa (1968) instead introduced the subgenus <i>Beszella</i> within the genus <i>Scaeva</i> Fabricius, 1805 to include <i>S. lapponica</i> (type species) and the Nearctic <i>Syrphus aberrantis</i> Curran, 1924. Most subsequent authors accepted the placement of <i>Lapposyrphus</i> as a subgenus of <i>Metasyrphus</i> (e.g. Vockeroth, 1969; Stubbs and Falk, 1983; Peck, 1988) or of <i>Eupeodes</i> Osten Sacken, 1877 (e.g. Vockeroth, 1992; Vockeroth and Thompson, 1992; Haarto and Kerppola, 2007). <i>Beszella</i> is considered a junior synonym of <i>Lapposyrphus</i> (Peck, 1988), although many authors do not mention it at all in their works (e.g. Vockeroth, 1992; Vockeroth and Thompson, 1992).</p>
  <p>Recent molecular data, however, support the recognition of <i>Lapposyrphus</i> as a separate genus, forming a cluster together with genera related to <i>Eupeodes</i>, although phylogenetic relationships inside this group of genera are not always fully resolved (Mengual et al., 2008, 2018, 2023). For example, Mengual et al. (2018) recovered <i>Lapposyrphus</i> as the outgroup to a cluster formed by <i>Simosyrphus</i> Bigot, 1882, <i>Pseudodoros</i> Becker, 1903, <i>Ischiodon</i> Sack, 1913, <i>Scaeva</i>, <i>Dioprosopa</i> Hull, 1949, <i>Notosyrphus</i> Vockeroth, 1969, and <i>Austroscaeva</i> Láska, Mazánek & Mengual, 2018. Mengual et al. (2023) instead proposed <i>Lapposyrphus</i> as the outgroup to the cluster comprising the three Neotropical genera <i>Dioprosopa</i>, <i>Notosyrphus</i>, and <i>Austroscaeva</i>.</p>
  `, 
  diagnosis: `
    <p>Dušek and Láska (1967) introduced the genus <i>Fagisyrphus</i> including the single species <i>Scaeva cincta</i> Fallén, 1817. Hippa (1968) do not cite the genus. Vockeroth (1969) considered <i>Fagisyrphus</i> a hypothetical subgenus of <i>Melangyna</i> Verrall, 1901. Some authors have regarded <i>Fagisyrphus</i> as a synonym of <i>Melangyna</i> (e.g. Peck, 1988; Rotheray and Gilbert, 1989; Verlinden, 1991; van Veen, 2004); other authors, especially more recently, have instead treated <i>Fagisyrphus</i> as a valid genus (e.g. Torp, 1994; Haarto and Kerppola, 2007; Bartsch et al., 2009; Bot and van de Meutter, 2023).</p>
    <p>Recent molecular data consistently support a close relationship between <i>Fagisyrphus</i> and <i>Meligramma</i> Frey, 1946, but not with <i>Melangyna</i> (Mengual et al., 2008, 2018, 2023). The relationship between the clade formed by <i>Meligramma</i> + <i>Fagisyrphus</i> and other genera of Syrphini is, however, more uncertain. Mengual et al. (2008) reported a close relationship of these two genera with <i>Dasysyrphus</i>, whereas Mengual et al. (2023) considered <i>Meligramma</i> + <i>Fagisyrphus</i> as the sister group of a clade including <i>Leucozona</i> Schiner, 1860, <i>Epistrophella</i> Dušek and Láska, 1967, <i>Epistrophe</i> Walker, 1852, and <i>Afrosyrphus</i> Curran, 1927. In any case, <i>Fagisyrphus</i> + <i>Meligramma</i> do not appear to be phylogenetically close to <i>Melangyna</i>, and therefore synonym with this genus should be excluded.</p>`,

  description: `
    <p>The face is yellow and covered with tomentum except in the central part; a black vitta running dorsoventrally from the oral margin to the facial tubercle is absent. The face is covered with yellow hairs. The oral margin is yellow. The eyes are bare. Males are holoptic, females dichoptic. In males, the frons is yellow, with tomentum present. In females, the frons is yellow except around the ocellar triangle and for a central vitta extending from the ocellar triangle for more than half the length of the frons. The frons is covered with tomentum except on the black area around the ocellar triangle and centrally. The hairs on the frons are yellow. The antennae are simple, yellow‑reddish, brownish on the upper margin. The basiflagellomere is approximately as long as wide. The arista is black. The occiput is whitish due to extensive tomentum; the hairs are yellow.</p>
    <p>The scutum is black and shiny with two marginal yellow vittae extending from the postpronotum to posterior margin; scutal hairs are long and yellow. The scutellum is completely yellow, bearing yellow hairs. The pleura are black, with large yellow spot on antepronotum, posterior anepisternum, katepisternum (dorsally), katepimeron and katatergum and largely covered with tomentum. Pleural hairs are long and yellow. The metasternum is bare.</p>
    <p>The legs are simple and entirely yellow. The hairs on the fore and mid legs are yellow and short, except on the posterior surface of the femora, where long hairs are present. The hairs on the hind legs are yellow, except on the apical part of the femora and on dorsal surface of the tibiae and tarsomeres, where short black hairs are present. The wings are hyaline and completely covered with microtrichia, except for cells bm and br, which show areas devoid of microtrichia over less than half of their surface. The vein R4+5 is straight. The halteres are yellow. No long hairs are present on the dorsal surface of the calypters.</p>
    <p>The abdomen is unmarginate, with parallel sides. It is black, with yellow spots on tergites 2 and large yellow band on tergites 3-5. Tergite hairs are mainly yellow on tergite 2; on tergites 3-5 hairs are short and mainly black (yellow hairs are present along the anterior lateral margin of the tergites). The sternites are yellow; the hairs are yellow on sternites 1, 2 and on the anterior fourth of sternite 3, while from sternites 3 onwards the hairs are black.</p>
    <p>In the male genitalia the epandrium is trapezoidal in lateral view, and the hypandrium is rounded ventrally, with a long and evident ventral lingula. The postgonite is squared, with the distal margin curved and crossed dorsoventrally by a flange. The surstyli are short, apically tapering, and with a basal swelling that makes the proximal part broadened. The cerci are oval and bear long hairs. The basiphallus is strongly laterally compressed and bears two ventral teeth, with the distal one more developed. The distiphallus is long and apically compressed.</p>
    `,  
  biology:`
  <p>The larvae of the genus are zoophagous. Morphologically, they are similar to those of <i>Melangyna</i>, with a marked dorso‑ventral flattening; the lateral margins are not serrated. The larval coloration is greenish, with conspicuous white fat bodies. The larvae develop at the expense of aphids associated with beech. Adults occur in forested habitats, especially beech woods, oak forests, and alluvial woodlands. The larva overwinters in the litter, and the life cycle is bivoltine. <i>Fagisyrphus cinctus</i> is occasionally migratory.</p>
  `,
  biodiversity: `
  <p>The genus includes only one species (Evenhuis & Pape, 2026): <i>Fagisyrphus cinctus</i>. The species is widely distributed in Europe, although it is rarer around the Mediterranean and in the far north; it has also been reported from Georgia and Turkey (Reverté et al., 2023; Speight et al., 2024). According to Vockeroth (1980), records of this species from North America are erroneous.</p>
  `,
  italianBiodiversity: `
 <p><i>Fagisyrphus cinctus</i> is reported from across the Italian peninsula, although records from the southern regions are rarer. There is also a record from Sicily (Sommaggio, 2005). No records are known from Sardinia.</p>
 `,
  references: [
    'Bartsch, H., Binkiewicz, E., Rådén, A. & Nasibov, E. (2009a) Blomflugor: Syrphinae. Nationalnyckeln till Sveriges flora och flora, DH53a. Artdatabanken, SLU, Uppsala. 406 pp.',
    'Bot, S., van de Meutter, F. (2023). Hoverflies of Britain and North-west Europe. A photographic guide. Bloomsbury Wildlife, London, 400 pp.',
    'Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.',
    'Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href="http://diptera.org/" target="_blank">http://diptera.org/</a> [accessed on 25.08.2025]',
    'Haarto, A., Kerppola, S. (2007) Finnish hoverflies and some species in adjacent countries. Otavan Kirjapaino Oy, Keuruu. 647pp.',
    'Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.',
    'Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 2023, 48: 250-277. <a href="https://doi.org/10.1111/syen.12573" target="_blank">https://doi.org/10.1111/syen.12573</a>',
    'Mengual, X., Ståhls, G., Láska, P., Mazánek, L., Rojo, S. (2018) Molecular phylogenetics of the predatory lineage of flower flies <i>Eupeodes</i>-<i>Scaeva</i> (Diptera: Syrphidae), with the description of the Neotropical genus <i>Austroscaeva</i> gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56: 148-169.',
    'Mengual, X., Ståhls, G. & Rojo, S. (2008) First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href="https://doi.org/10.1111/j.1096-0031.2008.00200.x" target="_blank">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>',
    'Peck, L.V. (1988) Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.',
    'Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775. ',
    'Rotheray, G.E. & Gilbert, F.S. (1989) The phylogeny and systematics of European predaceous Syrphidae (Diptera) based on larval and puparial stages. Zoological Journal of the Linnean Society, 95: 29-70.',
    'Sommaggio, D. (2005) Insecta Diptera Syrphidae (Syrphinae, Syrphini). In Ruffo S., Stoch F. (eds). Checklist and distribution of Italian fauna. Memorie del Museo Civico di Storia Naturale di Verona. 2Serie. Sezione Scienze della Vita, 16.',
    'Speight, M.C.D. (2024) Species accounts of European Syrphidae, 2024. Syrph the Net, the database of European Syrphidae (Diptera), vol. 115, 381 pp., Syrph the Net publications, Dublin.',
    'Torp, E. (1994) Danmarks Svirrefluer (Diptera: Syrphidae). Danmarks Dyreliv, 6: 1-490. Apollo books, Stenstrup.',
    'Veen, van M.P. (2004). Hoverflies of Northwest Europe. Identification keys to the Syrphidae. KNNV Publishing, 254 pp.',
    'Verlinden, L. (1994) Fauna de Belgique: Syrphides (Syrphidae). Institut Royal des Sciences Naturelles de Belgique, Brussels. pp. 289.',
    'Vockeroth, J.R., (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176.',
    'Vockeroth, J.R. (1980) A review of the Nearctic species of Melangyna (Meligramma) Frey (Diptera: Syrphidae). The Canadian Entomologist, 122: 775-778.'
 ]
}

export default Fagisyrphus
