const Ischiodon = {
  otuId: 1025181,
  taxonName: 'Ischiodon',
  author: 'Sack, 1913',
  url: '/otus/1025181/overview',
  keyUrl: '',
  keyUrlEN: '',
  numSpecies: '4',
  numSpeciesIta: '1',
  distribution: ['Afrotropical', 'Australasian', 'Indomalayan', 'Palearctic'],
  introduction: `<p>The genus <i>Ischiodon</i> was established by Sack (1913) to accommodate the new species <i>I. trochanterica</i>, now considered a synonym of <i>Ischiodon scutellaris</i> (Fabricius, 1805) (e.g. Peck, 1988; Mengual, 2018). The species currently included in <i>Ischiodon</i> were previously placed in several different genera, particularly <i>Syrphus</i> Fabricius, 1775, <i>Sphaerophoria</i> Le Peletier & Serville, 1828, <i>Xanthogramma</i> Schiner, 1860, and <i>Scaeva</i> Fabricius, 1805. The genus <i>Ischiodon</i> has also been confused with <i>Simosyrphus</i> Bigot, 1882 (Vockeroth, 1969; Mengual, 2018). Although Vockeroth (1969) acknowledged the strong external morphological similarity between <i>Simosyrphus grandicornis</i> (Macquart, 1842) and species of <i>Ischiodon</i>, he considered the two genera valid, mainly due to differences in the male genitalia. Mengual et al. (2018, 2023), based on molecular evidence, confirmed the validity of both genera (<i>Ischiodon</i> and <i>Simosyrphus</i>), which together with <i>Pseudodoros</i> Becker, 1903, form the sister group to the genus <i>Scaeva</i>.</p>
`, 
diagnosis: `
<p>The genus <i>Ischiodon</i> can be readily distinguished from other genera of the tribe Syrphini (bare humeri; scutellum and/or face at least partly yellow) by the following combination of characters: calypter without dorsal hairs; eyes bare; abdomen marginate; notum with evident  yellow vittae along the margin; metasternum bare; vein R4+5 almost straight; the microtrichia on wing are greatly reduced (the cell bm is almost virtually free of microtrichia).</p>
<p>Males of this genus can be easily separated from all other Syphini by the presence of an apically acute ventral process on the trochanter of mid and hind legs, at least in European species. Females can be distinguished from similar genera by the following features:</p>
<ul>
  <li><i>Lapposyrphus</i> Dusek & Laska, 1967: in <i>Ischiodon</i> vein R4+5 is almost straight (curved in <i>Lapposyrphus</i>); the yellow vittae on the notum are distinct; and the wing microtrichia are greatly reduced.</li>
  <li><i>Eupeodes</i> Osten Sacken, 1877: in <i>Ischiodon</i> the metasternum is bare (hairy in <i>Eupeodes</i>); the yellow vittae on the notum are distinct; and the wing microtrichia are greatly reduced (well developed in most <i>Eupeodes</i>, except a few species such as <i>E. lundbecki</i> (Soot‑Ryen, 1946)).</li>
  <li><i>Scaeva</i>: in <i>Ischiodon</i> the eyes are bare (hairy in <i>Scaeva</i>).</li>
</ul>
`,
  description: `
<p>The face, including the oral margin, is yellow and lacks a black vitta; it is covered with yellow hairs. The eyes are bare. Males are holoptic, females dichoptic. In males, the frons is yellow and lacks tomentum. In females, the posterior part of the frons is shiny black, extending over approximately one quarter of the total frons length (from anterior ocellus to the lunulae). In addition, in females a black vitta extends from the posterior dark area to the lunule. The female frons is entirely devoid of tomentum. The hairs on the frons are short and yellowish in males; in females, they are black on the posterior third and yellow anteriorly. The antennae are simple and yellow, except in females, which bear a dorsal black stripe on both the scape and pedicel. The postpedicel is oval and elongated, almost 2.5 times longer than wide and approximately three times the combined length of the scape and pedicel. The occiput is whitish due to extensive tomentum, which may be absent behind the ocellar triangle; the occiput is entirely covered with whitish hairs.</p>
<p>The scutum is black and shiny; two longitudinal yellow vittae are present laterally, extending from the postpronotum to the posterior angles. Scutal hairs are whitish. The scutellum is yellow, bearing whitish hairs that are approximately one third of the scutellum length in males and one quarter or less in females. The pleura are black and shiny, with long whitish hairs. Yellow patches are present dorsally on the katepisternum and on the posterior half of posterior anepisternum. The metasternum is bare.</p>
<p>The legs are simple, except for the male hind trochanters, which bear a spina in <I>I</I>. <i>aegyptius</i> (Wiegmann, 1830)and <I>I</I>. <i>scutellaris</i>. The coxae are black; the trochanters are yellow, at least on their posterior half. The remainder of the legs is yellow, except that the hind femora and tibiae may bear a dark ring, and the hind tarsi which usually are black dorsally. Leg hairs are yellow, except dorsally on the hind tarsi. The wings are hyaline; microtrichia are strongly reduced, with the basal half of the wing almost completely devoid of them, while in the apical half they are present but sparse. Vein R4+5 is practically straight. The halteres are yellow. No long hairs are present on the dorsal surface of the calypters.</p>
<p>The abdomen is clearly marginate, elongated, with parallel lateral margins. Tergite 1 is black and shiny; tergite 2 is black with a yellow band<i> (I</i>. <i>aegyptius</i>) or yellow spots (<i>I. scutellaris</i>, <i>I. feae </i>(Bezzi, 1912)<i> </i>and <i>I. astales </i>Mengual, 2018). Tergites 3 and 4 are black with yellow bands, except in <i>I. feae</i>. The hairs on the tergites are short, yellow on the anterior half and black on the posterior half. The marginal hairs of the tergites are black from tergite 3 onwards, except for a few yellow hairs at the base of tergite 3. The sternites are yellow, with a small central black spot, generally absent on sternite 4. The hairs of the sternites are yellow and short, except on sternite 1 and centrally on sternite 2, where they are longer.</p>
<p>The male genitalia are extremely variable. The epandrium is trapezoidal; the hypandrium is variable, and in the Italian species<i> (I</i>. <i>aegyptius</i>) bears two small posterior projections. The surstyli are long and highly variable: in <i>I. aegyptius</i> they are trilobed, whereas in <i>I. scutellaris</i> they are elongated, with the apical portion wider than the basal one. The postgonites are well developed and generally bear one or two dorsal teeth. The cerci are oval and bear long hairs. The basiphallus is strongly laterally compressed and bears a single ventral tooth. The distiphallus is variable: it is very elongated in <i>I. astales</i>, whereas in <i>I. aegyptius</i> and <i>I. scutellaris</i> it bears two ventral lobes.</p>
`,  
  biology:`
  <p>The larvae of the genus are zoophagous. They are oval in cross section, and the body is green with a whitish stripe along the dorsal midline. Locomotory prominences are well developed on abdominal segments 1–7. The larvae prey on aphids on low growing plants, shrubs, and small trees. Rojo et al. (2003) reported <i>I. aegyptius</i> as a predator of whiteflies, thrips, and lepidopteran larvae.Both <i>I. aegyptius</i> and <i>I. scutellaris</i> have also been recorded on crops.</p>
  <p>Adults occur in a broad range of habitats, from evergreen forests to Mediterranean shrublands, and from xeric–semi arid grasslands to agroecosystems. Development is short, and the species are multivoltine. Both <i>I. aegyptius</i> and <i>I. scutellaris</i> are migratory; in recent years <i>I. aegyptius</i> appears to be expanding its distribution northwards, possibly as a consequence of climate change.</p>
 `,
  biodiversity: `
  <p>The genus is small and includes only four species (Mengual, 2018). Two species are endemic to Africa: <i>Ischiodon feae</i>, restricted to Cape Verde, and <i>I. aestivalis</i> from Madagascar. The other two species have a much wider distribution. <i>Ischiodon aegyptius</i> occurs throughout Africa and extends northwards into southern Europe. <i>Ischiodon scutellaris</i> is widespread in Asia, including India, and has also been reported from Australia and the Indo Malayan region.</p>
  <p>In Europe, only these two species are present (Reverté et al., 2023): <i>I. aegyptius</i> is more broadly distributed across southern European countries, whereas <i>I. scutellaris</i> is known only from Greece and Ukraine.</p>
  `,
  italianBiodiversity: `
  <p>In Italy, only <i>I. aegyptius</i> has been recorded. In the past, this species was known only from a few regions in central and southern Italy (Lazio and Sicily). However, it has recently been reported also from Veneto (Lorenzato et al., 2024).</p>
  `,
  references: [
    'Mengual X., 2018. A new species of <i>Ischiodon</i> Sack (Diptera, Syrphidae) from Madagascar. African Invertebrates 59(1): 55–73',
    'Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 2023, 48: 250-277. <a href="https://doi.org/10.1111/syen.12573" target="_blank">https://doi.org/10.1111/syen.12573</a>',
    'Mengual, X., Ståhls, G., Láska, P., Mazánek, L., Rojo, S. (2018) Molecular phylogenetics of the predatory lineage of flower flies <i>Eupeodes</i>-<i>Scaeva</i> (Diptera: Syrphidae), with the description of the Neotropical genus <i>Austroscaeva</i> gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56: 148-169.',
    'Peck, L.V. (1988) Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.',
    'Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775. ',
    'Rojo, S., Gilbert, F., Marcos-García, M-A., Nieto, J.M., Mier, M.P. (2003) <i>A world review of predatory hoverflies (Diptera, Syrphidae: Syrphinae) and their prey</i>. 319 pp. CIBIO Ediciones, Alicante',
    'SacK, P. (1913). H. Sauter`s Formosa-Ausbeute: Syrphiden I. (Dipt.). Entomologische Mitteilungen 2: 1-10.',
    'Vockeroth, J.R., (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society oEntomological Society of Canada 62: 1-176.'
]
}

export default Ischiodon
