const Lapposyrphus = {
  otuId: 1025210,
  taxonName: 'Lapposyrphus',
  author: 'Dušek and Láska, 1967',
  url: '/otus/1025210/overview',
  keyUrl: '',
  keyUrlEN: '',
  numSpecies: '2',
  numSpeciesIta: '1',
  distribution: ['Nearctic', 'Palearctic'],
  introduction: `
  <p>Dušek and Láska (1967) introduced the subgenus <i>Lapposyrphus</i> within the genus <i>Metasyrphus</i> Matsumura, 1917 to accommodate the single species <i>Scaeva lapponica</i> Zetterstedt, 1838. Hippa (1968) instead introduced the subgenus <i>Beszella</i> within the genus <i>Scaeva</i> Fabricius, 1805 to include <i>S. lapponica</i> (type species) and the Nearctic <i>Syrphus aberrantis</i> Curran, 1924. Most subsequent authors accepted the placement of <i>Lapposyrphus</i> as a subgenus of <i>Metasyrphus</i> (e.g. Vockeroth, 1969; Stubbs and Falk, 1983; Peck, 1988) or of <i>Eupeodes</i> Osten Sacken, 1877 (e.g. Vockeroth, 1992; Vockeroth and Thompson, 1992; Haarto and Kerppola, 2007). <i>Beszella</i> is considered a junior synonym of <i>Lapposyrphus</i> (Peck, 1988), although many authors do not mention it at all in their works (e.g. Vockeroth, 1992; Vockeroth and Thompson, 1992).</p>
  <p>Recent molecular data, however, support the recognition of <i>Lapposyrphus</i> as a separate genus, forming a cluster together with genera related to <i>Eupeodes</i>, although phylogenetic relationships inside this group of genera are not always fully resolved (Mengual et al., 2008, 2018, 2023). For example, Mengual et al. (2018) recovered <i>Lapposyrphus</i> as the outgroup to a cluster formed by <i>Simosyrphus</i> Bigot, 1882, <i>Pseudodoros</i> Becker, 1903, <i>Ischiodon</i> Sack, 1913, <i>Scaeva</i>, <i>Dioprosopa</i> Hull, 1949, <i>Notosyrphus</i> Vockeroth, 1969, and <i>Austroscaeva</i> Láska, Mazánek & Mengual, 2018. Mengual et al. (2023) instead proposed <i>Lapposyrphus</i> as the outgroup to the cluster comprising the three Neotropical genera <i>Dioprosopa</i>, <i>Notosyrphus</i>, and <i>Austroscaeva</i>.</p>
  `, 
diagnosis: `
<p>The genus <i>Lapposyrphus</i> can be readily distinguished from other genera of the tribe Syrphini (bare humeri; scutellum and/or face at least partly yellow) by the following combination of characters: calypter without dorsal hairs; eyes bare; abdomen with a clearly marginate, at least on tergites 4 and 5; abdominal margin bearing only black hairs from the third tergite onward; notum without yellow vittae along the margin; metasternum bare; vein R4+5 with a dip in the cell r4+5, the abdomen is black with yellow spots.</p>
<p>The genus is particularly close to <i>Eupeodes</i>, but it can nevertheless be easily distinguished by the shape of vein R4+5, which shows a distinct dip in cell r4+5 (almost straight in <i>Eupeodes</i>), and by the bare metasternum (hairy in <i>Eupeodes</i>). The single European species (<i>L. lapponicus</i>) has a black abdomen with spots that have a concave anterior margin and a lateral portion narrower than the central one.</p>
`,
  description: `
<p>The face is yellow, with a black vittae running dorsoventrally from the oral margin to the facial tubercle. The face is covered with yellow hairs. The oral margin is yellow, becoming black only under centrally and along the margin. The eyes are bare. Males are holoptic, females dichoptic. In males the frons is yellow, with tomentum present on the proximal half. In females, the frons is black, yellow only on the anterior fourth, with two large lateral patches of tomentum; these tomentose patches leave the central area bare and shiny, corresponding to roughly one fifth to one quarter of the frons width. The hairs on the frons are black. The antennae are simple, yellow reddish ventrally and dark brown dorsally. The basiflagellomere is about twice as long as wide in males, whereas in females it is less elongated, reaching at most 1.5 times as long as wide. The occiput is whitish due to extensive tomentum; the hairs are yellow, with possibly a few black hairs in the upper part. </p>
<p>The scutum is black and shiny; scutal hairs are long and yellow. The scutellum is yellow, with small black spots at the anterior angles. The hairs of the scutellum are long and mainly black; few yellow hairs are present along the margin of the scutellum. The pleura are black and largely covered with tomentum. Pleural hairs are long, yellow and apically wavy. The metasternum is bare.</p>
<p>The legs are simple; the coxae and trochanters are black. The fore and mid femora are yellow, with the basal quarter black in males and less in females; the fore and mid tibiae and tarsi are entirely yellow, except tarsomeres 2–4, which may be darker dorsally. The hind femora are yellow, sometimes with a darker ring in the central part; the tibiae are yellow, with or without a darker central ring. The hind tarsomeres are black, especially the apical ones (from the second onwards), and particularly in females. The hairs on the fore and mid legs are yellow and short, except on the posterior surface of the femora, where numerous long hairs are present. The hairs on the hind legs are black and short, except for some very long yellow hairs on the posterior surface of the femora; short yellow hairs are also present on the ventral side of the tarsomeres and on the anterior surface of the tibiae. The wings are hyaline and completely covered with microtrichia, except for cells bm and br, which show areas devoid of microtrichia over more than half of their surface; the alula also has a central area lacking microtrichia. The vein R4+5 has a clear dip in the cell r4+5. The halteres are yellow. No long hairs are present on the dorsal surface of the calypters.</p>
<p>The abdomen is clearly marginate. It is black with yellow spots on tergites 2–5; the spots are separate, except in very rare cases where a slight connection may be present in spots of tergites 3 and 4. The spots on tergites 3 and 4 have a concave anterior margin and are often narrower laterally. Tergite 5 has entirely black lateral margins. Tergite hairs are mainly yellow and erect in males, with black hairs present along the lateral and posterior margins. In females, the hairs are mainly short, black and adpressed; short yellow hairs are present along the anterior margin. From the posterior half of the second tergite onwards, the hairs on the lateral margins of the tergites are entirely black. The sternites are yellow, with a more or less extended central black spot, which in some cases may form a band on the posterior margin that extends anteriorly in the centre and along the lateral margins. The hairs of the sternites are usually long and yellow, although black hairs may be present from the third sternite onwards.</p>
<p>In the male genitalia the epandrium is trapezoidal in lateral vew, and the hypandrium is rounded ventrally, with a short and evident ventral lingula. The surstyli are long and usually taper apically. The postgonites are broader at the base and rounded apically. The cerci are oval and bear long hairs. The basiphallus is strongly laterally compressed and bears two ventral teeth. The distiphallus is long and apically compressed.</p>
`,  
  biology:`
  <p>The larvae of the genus are zoophagous. They are sub cylindrical, whitish with small brown spots. The larvae develop at the expense of aphids living in the arboreal layer, both on conifers (e.g. <i>Abies</i>, <i>Picea</i>) and on deciduous trees (e.g. <i>Fagus</i>, <i>Euonymus</i>). Adults occur in forested habitats, on deciduous trees (<i>Fagus</i>, <i>Quercus pubescens</i>) but more commonly on conifers (<i>Abies</i>, <i>Picea</i>, <i>Pinus</i>, <i>Larix</i>). The larva overwinters in the litter; the life cycle is bivoltine. <i>Lapposyrphus lapponicus</i> is occasionally migratory.</p>
  `,
  biodiversity: `
  <p>The genus includes only two species (Evenhuis & Pape, 2026): <i>Lapposyrphus lapponicus</i> and <i>L. aberrantis</i>. The former has a wide distribution and is known from the Holarctic region. In contrast, <i>L. aberrantis</i> is recorded from North America. The only European species is widely distributed in central and northern Europe, including the mountainous areas of the Balkans (Reverté et al., 2023).</p>
   `,
  italianBiodiversity: `
 <p><i>Lapposyrphus lapponicus</i> is a common species along the Alpine arc; records from central Italy are more limited, although it has been reported from Toscana, Abruzzo, Marche and Basilicata regions. The species has not been recorded from Sardegna or Sicilia regions.</p>
  `,
  references: [
    'Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.',
    'Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href="http://diptera.org/" target="_blank">http://diptera.org/</a> [accessed on 25.08.2025]',
    'Haarto, A., Kerppola, S. (2007) Finnish hoverflies and some species in adjacent countries. Otavan Kirjapaino Oy, Keuruu. 647pp.',
    'Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.',
    'Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 2023, 48: 250-277. <a href="https://doi.org/10.1111/syen.12573" target="_blank">https://doi.org/10.1111/syen.12573</a>',
    'Mengual, X., Ståhls, G., Láska, P., Mazánek, L., Rojo, S. (2018) Molecular phylogenetics of the predatory lineage of flower flies <i>Eupeodes</i>-<i>Scaeva</i> (Diptera: Syrphidae), with the description of the Neotropical genus <i>Austroscaeva</i> gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56: 148-169.',
    'Mengual, X., Ståhls, G. & Rojo, S. (2008) First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href="https://doi.org/10.1111/j.1096-0031.2008.00200.x" target="_blank">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>',
    'Peck, L.V. (1988) Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.',
    'Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775. ',
    'Stubbs, A.E., Falk, S.J. (1983). <i>British hoverflies: an illustrated identification guide</i>. British Entomological and Natural History Society, London, 253 pp.',
    'Vockeroth, J.R., (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176.',
    'Vockeroth, J.R. (1992). <i>The flower flies of the subfamily Syrphinae of Canada, Alaska, and Greenland (Diptera: Syrphidae).</i> The Insects and Arachnids of Canada, Part 18. Research Branch, Agriculture Canada, Ottawa, 343 pp.',
    'Vockeroth, J.R., Thompson, F.C. (1987). Syrphidae. In: McAlpine, J.F. et al. (eds), <i>Manual of Nearctic Diptera</i>, Volume 2. Agriculture Canada, Research Branch, Ottawa. Monograph No. 28: 713–743.'
    ]
}

export default Lapposyrphus
