const Leucozona = {
  otuId: 1025369,
  taxonName: 'Leucozona',
  author: 'Schiner, 1860',
  url: '/otus/1025369/overview',
  keyUrl: '',
  keyUrlEN: '',
  numSpecies: '16',
  numSpeciesIta: '3',
  distribution: ['Indomalayan', 'Nearctic', 'Palearctic'],
  introduction: `
<p>Schiner (1860) introduced the genus <i>Leucozona</i> to accommodate the single species <i>Musca lucorum</i> Linnaeus, 1758. Later, Bigot (1882) established the genus <i>Ischyrosyrphus</i>, designating the new species <i>Ischyrosyrphus sivae</i> Bigot, 1882 as its type species. Verrall (1901) regarded both genera as valid, but erroneously stated that <i>Musca glaucia</i> Linnaeus, 1759 was the type species designated by Bigot. Subsequent authors continued to treat the two genera as valid, and also included <i>Syrphus leiophthalmus</i> Schiner & Egger, 1854, which is now considered to belong to the genus <i>Epistrophe</i> Walker, 1852 (Verrall, 1901; Bezzi & Stein, 1907; Sack, 1930; Séguy, 1961; Dušek & Láska, 1967). Mik (1897) introduced the new genus <i>Lagenosyrphus</i> to include <i>Syrphus leiophthalmus</i>; however, this genus was not accepted by later authors and was treated as a synonym of <i>Ischyrosyrphus</i> (e.g. Verrall, 1901; Bezzi & Stein, 1907; Sack, 1930; Séguy, 1961) or, more recently, of <i>Epistrophe</i> (e.g. Vockeroth, 1969; Peck, 1988).</p>
<p>Hippa (1968) and Vockeroth (1969) considered <i>Leucozona</i> and <i>Ischyrosyrphus</i> to be very closely related, and Hippa (1968) treated <i>Ischyrosyrphus</i> as a subgenus of <i>Leucozona</i>. This interpretation was followed by some authors (e.g. Stubbs & Falk, 1983; Haarto & Kerppola, 2007), although most authors have regarded <i>Ischyrosyrphus</i> as a synonym of <i>Leucozona</i> (e.g. van Veen, 2004; Bartsch et al., 2009; Bot & de Meutter, 2023).</p>
<p>Molecular data confirm the close relationship between <i>Leucozona</i> and <i>Ischyrosyrphus</i>, although they do not resolve whether the latter should be treated as a subgenus of <i>Leucozona</i> or as its synonym (Mengual et al., 2008, 2018, 2023). The phylogenetic position of <i>Leucozona</i> remains debated: Mengual et al. (2018, 2023) recovered <i>Leucozona</i> as the outgroup to <i>Epistrophella</i> Dušek & Láska, 1967, <i>Epistrophe</i> and <i>Afrosyrphus</i> Curran, 1927, whereas Mengual et al. (2008) placed <i>Leucozona</i> as the outgroup of a much broader clade including, among others, <i>Syrphus</i> Fabricius, 1775, <i>Dasysyrphus</i>, Enderlein, 1938, <i>Epistrophe</i>, <i>Parasyrphus</i> Matsumura, 1917, and <i>Scaeva</i> Fabricius, 1805.</p> `, 
diagnosis: `
<p>The genus <i>Leucozona</i> can be distinguished from other genera of the tribe Syrphini (bare humeri; scutellum and/or face at least partly yellow) by the following combination of characters: calypter without dorsal hairs; eyes with long hairs; abdomen clearly marginate, at least on tergites 4 and 5; abdominal margin bearing black and yellow hairs from the third tergite onward; notum lacking yellow marginal vittae; metasternum bare; vein R4+5 almost straight. The genus is easily recognized by its characteristic abdominal colour pattern: tergite 2 bears large yellowish or whitish spots occupying more than half of the tergite (only occasionally obscured by tomentosity), whereas the remaining tergites are entirely black or show patches of whitish tomentosity.</p>
<p><i>Leucozona</i> may be confused with <i>Eriozona</i>, but in the latter the spots on tergite 2 are absent and tergites 4 and 5 show a yellowish coloration. <i>Epistrophe leiophthalma</i> is another species that can be mistaken for <i>Leucozona</i>, but in <i>Epistrophe</i> the eyes are bare, the metasternum is hairy, and the abdomen is not marginate.</p>`,
  description: `
<p>The face is yellow, with or without a black vitta running dorsoventrally from the oral margin to the facial tubercle; the face may be covered with tomentum and therefore appear more whitish than yellow. The face is covered with yellow or whitish hairs. The oral margin is black (<i>Leucozona lucorum</i> and <i>L. inopinata</i>) or yellow (<i>L. glaucia</i> and <i>L. laternaria</i>). The eyes are covered with brownish hairs. Males are holoptic, females dichoptic. In males, the frons is centrally black and laterally yellow or black, and is broadly covered with tomentum, giving it a whitish appearance. In females, the frons is centrally black and laterally yellowish or black, but appears greyish because it is extensively covered with tomentum. The hairs on the frons are mainly black, or a mixture of black and yellow. The antennae are simple and black. The occiput is whitish due to extensive tomentum, which may be absent behind the ocellar triangle; the occiput bears long yellow‑white hairs, occasionally with a few black hairs.</p>
<p>The scutum is black and dull; the notopleuron may appear whitish due to the extensive development of tomentum. Scutal hairs are long and yellow. The scutellum ranges from entirely yellow to black with only the apex yellow; in any case, it is always dull. The hairs of the scutellum are long and yellow or whitish. The pleura are black, without yellow patches, but appear greyish—especially in the dorsal half—because they are extensively covered with tomentum. Pleural hairs are long and whitish. The metasternum is bare.</p>
<p>The legs are simple; the coxae and trochanters are black. The femora are black basally and yellow apically, with the extent of the black ranging from the basal half to almost entirely black. The tibiae range from completely yellow to yellow with the apical half black. The tarsomeres are either entirely yellow or entirely black. The fore and mid legs bear short yellow hairs, except on the posterior half of the femora, where the hairs are long and may include — or even be dominated by — black hairs depending on the species. The hairs on the hind legs are shorter than those on the fore and mid legs and range from yellow with a few intermixed black hairs to predominantly black, especially on the femora and tibiae. The wings are hyaline, or may bear a large central dark patch extending from the pterostigma to beyond the mid‑wing. The wing is completely covered with microtrichia, except for cells bm and br, which may show bare areas depending on the species. The halteres range from entirely yellow to almost entirely black. No long hairs are present on the dorsal surface of the calypters.</p>
<p>The abdomen is clearly marginate. It is black, except for the second tergite, which usually bears large yellow or white spots. The remaining tergites are black, in some species with tomentose patches on tergites 3 and 4. Tergite hairs are generally yellow on the first and second tergites and black on the third tergite. From the fourth tergite onward, the hairs are either black or yellow depending on the species. The hairs along the abdominal margin are entirely yellow up to the second tergite, and then become a mixture of yellow and black. The first sternite is yellow; the second is predominantly yellow, although a black apical area may be present. From the third sternite onward, the sternites are black, sometimes with basal tomentosum. The hairs of the sternites are usually long and yellow, although black hairs may be present from the third sternite onwards.</p>
<p>The epandrium is trapezoidal, and the hypandrium is rounded ventrally. The surstyli are short and rounded apically. The hypandrial lingula is well developed, long, and broad. The postgonites are broad and short, curved apically, with a pointed dorsal angle. The cerci are oval and bear long hairs. The basiphallus is strongly laterally compressed and bears two blunt points ventrally. The distiphallus is short and apically compressed.</p>`,  
  biology:`
<p>The larvae of the genus are zoophagous. Larvae are laterally flattened, with a sub‑triangular cross‑section; they are translucent, with a green or cream coloration. Larvae may be found associated with aphids on herbaceous or arboreal vegetation, and in some cases also with root‑layer aphids. They do not appear to be specialised on particular aphid species. Adults occur in a broad array of habitats, mainly forested environments. <i>Leucozona lucorum</i> is frequently found also in open habitats such as permanent meadows, whereas <i>L. laternaria</i> occurs also in fens and along brook edges. The larvae overwinter in the soil, usually in the litter. All European species are known to be univoltine. All species are non‑migratory.</p>`,
  biodiversity: `
<p>Sixteen species have been described to date (Evenhuis & Pape, 2026), of which eight in the nominal subgenus (<i>Leucozona Leucozona</i>) and eight in the subgenus <i>Leucozona</i> (<i>Ischyrosyrphus</i>). The genus is predominantly Palaearctic, with ten species recorded from this region. Three species are recorded from the Nearctic Region and three from the Indo‑Malayan Region. No species are known from tropical areas. In Europe, four species are recorded, widely distributed across central and northern Europe, whereas they are virtually absent from the Mediterranean region (Reverté et al., 2023).</p>
`,
  italianBiodiversity: `
<p>In Italy, only three of the four European species are recorded (to date, there are no records of <i>Leucozona inopinata</i> Dockzkal, 2000). In Italy the genus is known only from the Alpine arc, where the species are uncommon. In the northern Apennines, a few records exist for <i>Leucozona lucorum</i> (Linnaeus, 1758), the most common species of the genus. For the identification of the Italian species, all keys for central and northern Europe are applicable (e.g. van Veen, 2004; Bartsch et al., 2009; Bot & de Meutter, 2023).</p>`,
  references: [
    'Bartsch, H., Binkiewicz, E., Rådén, A. & Nasibov, E. (2009a) Blomflugor: Syrphinae. Nationalnyckeln till Sveriges flora och flora, DH53a. Artdatabanken, SLU, Uppsala. 406 pp.',
    'Bezzi, M., Stein P. (1907). Cyclorrapha Aschiza. Cyclorrapha Schizophora: Schizometopa. In: Becker, T., Bezzi, M., Kertész, K., Stein, P. (eds.): Katalog der palaarktischen Dipteren, Vol. 3. Budapest. Pp. 1-188.',
    'Bigot, J.M.F. (1882). Descriptions de quatre genres nouveaux de la tribu des Syphides (Syrphidae auctorum), ainsi que celles de deux nouvelles especes. Bulletin Bimensuel de la Société Entomologique de France, 1882(6): 78-79.',
    'Bot, S., van de Meutter, F. (2023). Hoverflies of Britain and North-west Europe. A photographic guide. Bloomsbury Wildlife, London, 400 pp.',
    'Duśek, J., Láska, P. (1967). Versuch zum Aufbau eines naturlichen Systems mitteleuropäische r Arten der Unterfamilie Syrphinae (Diptera). Acta Sci. Nat. Brno 1: 349-390.',
    'Evenhuis, N.L., Pape, T. (2025). Systema Dipterorum, Version 6.2. <a href="http://diptera.org/" target="_blank">http://diptera.org/</a> [accessed on 07.03.2026]',
    'Haarto, A., Kerppola, S. (2007) Finnish hoverflies and some species in adjacent countries. Otavan Kirjapaino Oy, Keuruu. 647pp.',
    'Hippa, H. (1968). A generic revision of the genus <i>Syrphus</i> an allied genera (Diptera, Syrphidae) in the palearctic region, with descriptions of the male genitalia. Actga Entomologica Fennica 25: 1-94.',
    'Mengual, X.; Mayer, C.; Burt, T.O.; Moran, K.M.; Dietz, L.; Nottebrock, G.; Pauli, T.; Young, A.D.; Brasseur, M.V.; Kukowka, S.; et al. (2023). Systematics and evolution of predatory flower flies (Diptera: Syrphidae) based on exon-capture sequencing. Systematic Entomology, 2023, 48: 250-277. <a href="https://doi.org/10.1111/syen.12573" target="_blank">https://doi.org/10.1111/syen.12573</a>',
    'Mengual, X., Ståhls, G., Láska, P., Mazánek, L., Rojo, S. (2018) Molecular phylogenetics of the predatory lineage of flower flies <i>Eupeodes</i>-<i>Scaeva</i> (Diptera: Syrphidae), with the description of the Neotropical genus <i>Austroscaeva</i> gen. nov. Journal of Zoological Systematics and Evolutionary Research, 56: 148-169.',
    'Mengual, X., Ståhls, G. & Rojo, S. (2008) First phylogeny of predatory flower flies (Diptera, Syrphidae, Syrphinae) using mitochondrial COI and nuclear 28S rRNA genes: conflict and congruence with the current tribal classification. Cladistics, 24, 543–562. <a href="https://doi.org/10.1111/j.1096-0031.2008.00200.x" target="_blank">https://doi.org/10.1111/j.1096-0031.2008.00200.x</a>',
    'Mik, J. (1897). Einige Bemerkungen zur Dipteren-Familie der Syrphiden [part]. Wiener Entomologische Zeitung, 16: 61-66.',
    'Peck, L.V. (1988) Family Syrphidae. In: Soós, Á. & Papp, L. (eds.), Catalogue of the Diptera of the Palaearctic Region 8: 11-230.',
    'Reverté, S., Miličić, M., Ačanski, J., Andrić, A., Aracil, A., Aubert, M., Balzan, M.V., Bartomeus, I., Bogusch, P., et al. (2023). National records of 3000 European bee and hoverfly species: A contribution to pollinator conservation. Insect Conservation and Diversity, 16: 758-775. ',
    'Sack, P. (1930). 31. Syrphidae [part]. In: Lindner, E. (ed.): Die Fliegen der Palaearktischen Region 4(6): 177-240.',
    'Schiner, I.R. (1860). Vorlaufiger Commentar zum dipterologischen Theile der "Fauna Austriaca", mit einer naheren Begrundung der in derselben aufgenommenen neuen Dipteren-Gattungen. II. Wiener Entomologische Monatschrift, 4: 208-216.',
    'Séguy, E. (1961). Diptères: Syrphides. Mémoires du Muséum National d’Histoire Naturelle, Série A, Zoologie, Tome 23, 248 pp. ',
    'Stubbs, A.E., Falk, S.J. (1983). <i>British hoverflies: an illustrated identification guide</i>. British Entomological and Natural History Society, London, 253 pp.',
    'Veen, van M.P. (2004). Hoverflies of Northwest Europe. Identification keys to the Syrphidae. KNNV Publishing, 254 pp.',
    'Verrall, G.H. (1901). British flies. Vol. VIII, Platypezidae, Pipunculidae and Syrphidae of Great Britain. Gurney & Jackson, London. [i] + 691 pp. ',
    'Vockeroth, J.R., (1969). A revision of the genera of the Syrphini (Diptera: Syrphidae). The Memoirs of the Entomological Society of Canada 62: 1-176.',
    
    ]
}

export default Leucozona
